### PR TITLE
fix: Allow custom emoji in TOC

### LINKED ISSUE #11274: Custom Emojis in Headings show as "?" in TOC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This is not related to configuring Outline

- [x] The issue is not related to self-hosting config

### Current Behavior

Custom Emojis in Headings show as "?" in TOC:
Image

### Expected Behavior

Expect the custom emoji to show up in the TOC.

### Steps To Reproduce

running 1.3.0, add a custom emoji in a header and check the TOC

### Environment

```markdown
- Outline:1.3.0
- Browser:edge
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by tommoor**
closes #11274

### CODE REVIEW

File: app/menus/TableOfContentsMenu.tsx [hunk 1]
```diff
@@ -26,7 +27,7 @@ function TableOfContentsMenu() {
           createAction({
             name: (
               <HeadingWrapper $level={heading.level - minHeading}>
-                {t(heading.title)}
```
Comment (tommoor) [inline app/menus/TableOfContentsMenu.tsx:29]: No translation was needed here anyway, ugc
