### PR TITLE
Move document history to `revisions.list` API

### LINKED ISSUE #8403: Revision entry sometimes show wrong diff
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This is not related to configuring Outline

- [x] The issue is not related to self-hosting config

### Current Behavior

Sometimes, clicking on a fresh revision in the History page shows diffs from a prior change.

### Expected Behavior

_No response_

### Steps To Reproduce

1. Make a simple word insertion to a doc.
2. Wait for idle, until status says "You updated less than a minute ago"
3. `...` > History
4. Click on the latest (topmost) entry. The diff is wrong ❌ 
5. Click on the second latest entry, and then back to the latest entry. It's correct now ✔ 

### Environment

```markdown
`ac487671`
```

### Anything else?

_No response_

### LINKED ISSUE #8424: Move document history sidebar to be driven by `revisions.list`
As discussed, `events.list` will no longer be a reliable source of information.

### PR DESCRIPTION
**Pull request by hmacr**
Closes #8424 

This doesn't fix #8403 - it needs a bit more work to consolidate local document state.

I also noticed that document restore doesn't create a `documents.restore` event which sometimes messes up the history - will create a separate PR.

### CODE REVIEW

File: app/components/PaginatedList.tsx [hunk 1]
```diff
@@ -248,7 +251,9 @@ class PaginatedList<T extends PaginatedItem> extends React.PureComponent<
           }}
         </ArrowKeyNavigation>
         {this.allowLoadMore && (
-          <Waypoint key={this.renderCount} onEnter={this.loadMoreResults} />
+          <div style={{ height: "1px" }}>
```
Comment (hmacr) [inline app/components/PaginatedList.tsx:254]: I noticed that waypoint doesn't get triggered without a parent div. This happens only in the right sidebar though.. 🤔

File: server/routes/api/events/schema.ts [hunk 2]
```diff
@@ -15,7 +26,9 @@ export const EventsListSchema = BaseSchema.extend({
     /** Whether to include audit events */
     auditLog: z.boolean().default(false),
 
-    /** Name of the event to retrieve */
+    /** @deprecated, use 'events' instead
+     * Name of the event to retrieve
+     */
```
Comment (tommoor) [inline server/routes/api/events/schema.ts:31]:
```suggestion
    /** 
     * @deprecated, use `events` parameter instead
     * Name of the event to retrieve
     */
```

File: server/routes/api/events/events.ts [hunk 3]
```diff
@@ -20,37 +20,41 @@ router.post(
...
-      where = { ...where, actorId };
-    }
-
-    if (documentId) {
-      where = { ...where, documentId };
-    }
-
-    if (auditLog) {
+    if (events?.length) {
+      where.name = events;
```
Comment (tommoor) [inline server/routes/api/events/events.ts:38]: This will allow retrieving audit events without the `audit` policy, might be easiest to just filter?

File: app/scenes/Document/components/History.tsx [hunk 4]
```diff
@@ -1,34 +1,147 @@
...
+        createdAt: document.updatedAt,
+        actor: document.updatedBy!,
+        latest: true,
+      });
+    } else {
+      (latestRevision as RevisionEvent).latest = true;
+    }
+  }
+
+  const mergedEvents = orderBy(
```
Comment (tommoor) [inline app/scenes/Document/components/History.tsx:138]: Should memo this?

**Comment by hmacr** [comment]
> If the history is entirely driven from revisions then this should become a non-issue?

Yes, the whole impl becomes a lot simpler too - no need to keep track of individual offsets between revisions and events. Should be fine to just list the `revisions.list`?

File: server/routes/api/events/events.ts (hunk 3 above)
Comment (hmacr) [reply server/routes/api/events/events.ts:38]: Thanks for catching this bug.

**Comment by tommoor** [comment]
Well not sure I want to _remove_ them, I guess I'm just not sure how not having `documents.restore` is an issue here as we'll have an associated `revision`

**Comment by hmacr** [comment]
I hear you - I mean it's not a functional issue, just that the history might not have it which should be fine because data from events are _nice to haves_ anyway with the cleanup task going in later.

**Comment by tommoor** [comment]
Perhaps ideally there would be a separate model here like `DocumentHistory` that would combine revisions and events, leave events as the audit trail it was supposed to be.

Something for the future

**Review by tommoor — APPROVED** [review]
