### PR TITLE
fix: Include drafts when loading templates

### LINKED ISSUE #7099: Drafts are not included in the Templates page.
Draft templates are not displayed after refreshing the Templates page.

**To Reproduce**
1. Go to `Home` and then navigate to `Settings > Templates`.
2. Verify that the draft templates are displayed.
3. Refresh the page.
4. **Bug:** Draft templates are not displayed.

### PR DESCRIPTION
**Pull request by hmacr**
Closes #7099 

When the app is initially loaded, drafts are loaded into the store by the `App` sidebar.
This gets lost when the user navigates to templates settings & refreshes the page.

### CODE REVIEW

File: server/routes/api/documents/documents.ts [hunk 1]
```diff
@@ -97,7 +97,12 @@ router.post(
     };
 
     if (template) {
-      where = { ...where, template: true };
+      where = {
+        ...where,
+        template: true,
+        // override publishedAt filter from Document defaultScope to include drafts.
+        publishedAt: { [Op.or]: { [Op.eq]: null, [Op.ne]: null } },
```
Comment (tommoor) [inline server/routes/api/documents/documents.ts:104]: I think this will pull other users drafts, also it's a shame that it's so "hacky" of course. It might actually be better to just load drafts from the templates page and wait for both requests to complete. 🤔

Comment (hmacr) [reply server/routes/api/documents/documents.ts:104]: I wanted to avoid an additional API call; but if that's alright, cool :) Let me update the PR.

Comment (tommoor) [reply server/routes/api/documents/documents.ts]: Understandable, It'll be okay here given it's a settings page.

**Review by tommoor — APPROVED** [review]
