### PR TITLE
fix: Refactor collection exports to not send email attachment

### LINKED ISSUE #2125: Refactor collection exports to not send email attachment
Sending exports as an email attachment was perhaps a neat idea in the early days but we've reached the limit of what this can offer. Collections and their images regularly exceed the size that can be reliably sent over email. 

### User flow

- Generate the file on the event queue
- Upload the file to private storage bucket
- Email the user a link to download the export (The link should require a session)

### Considerations

As a security measure the emailed link should not be directly to the file, it should be to the web app which requires a session and forwards to a link generated to access storage.

In the future we may want to create a table to record exports, in this way we could immediately return an `export id` from the API when an export is requested and allow the end user to query the export progress

### PR DESCRIPTION
**Pull request by iamsaumya**
closes #2125 

I accidentally merged PR #2401.

### CODE REVIEW

**Comment by iamsaumya** [comment]
Ready for review 😄

**Comment by tommoor** [comment]
UX thoughts after testing these changes…

- [ ] "Recent exports" header is shown when there are no exports, lets just hide the section in that scenario
- [ ] Paragraph of text above "Export Data" button mentions emailing the zip, lets tweak that text to say that we'll email when the export is complete.
- [ ] Spacing here is tight, maybe throw a `<br />` between
    image
- [ ] This size is strange, I think the method needs a little more attention at low file sizes…
      image
- [ ] The "Download" button on exports appears before the operation is complete, clicking it results in an error. hide?
- [ ] Listing "complete" here is actually a bit confusing when you didn't see the export process – there isn't a lot of context, I'm not sure if that means it should be removed so we only show status when it's incomplete, maybe? image
- [ ] When triggering an individual collection export there is no feedback, maybe we should forward the user to `/settings/import-export`?

File: app/models/FileOperation.js [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+  state: string;
+  collection: ?Collection;
+  key: ?string;
+  size: number;
+  type: string;
+  user: User;
+  createdAt: string;
+
+  @computed
+  get sizeInMB(): string {
```
Comment (tommoor) [inline app/models/FileOperation.js:18]: As mentioned in comment, I think we need something slightly more sophisticated here that can deal with a wider range of sizes.

File: app/scenes/Settings/ImportExport.js [hunk 2]
```diff
@@ -199,6 +211,46 @@ function ImportExport() {
...
+            key={item.id}
+            title={
+              item.collection ? item.collection.name : t("All collections")
+            }
+            subtitle={
+              <>
+                <Flex>
+                  {stateMapping[item.state]}&nbsp;•&nbsp;
+                  {user.id === item.user.id ? t("You") : item.user.name}{" "}
+                  created&nbsp;
```
Comment (tommoor) [inline app/scenes/Settings/ImportExport.js:232]: Missing translation hook here, we should make sure to include the subject to get a proper translation – something like:

```javascript
t(`{{userName}} requested`, { userName: user.id === item.user.id ? t("You") : item.user.name})
```

File: app/scenes/Settings/ImportExport.js [hunk 3]
```diff
@@ -199,6 +211,46 @@ function ImportExport() {
...
+                onClick={() =>
+                  window.open(
+                    `/api/fileOperations.redirect?id=${item.id}`,
+                    "_blank"
+                  )
+                }
+                neutral
+              >
+                {t("Download")}
+              </Button>
```
Comment (tommoor) [inline app/scenes/Settings/ImportExport.js:249]: I _believe_ this will work

```suggestion
              <Button
                as="a"
                href={`/api/fileOperations.redirect?id=${item.id}`}
                neutral
              >
                {t("Download")}
              </Button>
```

File: server/api/collections.js [hunk 4]
```diff
@@ -454,25 +454,21 @@ router.post("collections.export", auth(), async (ctx) => {
...
-    data: { title: collection.title },
-    ip: ctx.request.ip,
-  });
+  exportCollections(user.teamId, user.id, user.email, id);
 
-  ctx.attachment(`${collection.name}.zip`);
-  ctx.set("Content-Type", "application/force-download");
-  ctx.body = fs.createReadStream(filePath);
+  ctx.body = {
+    success: true,
```
Comment (tommoor) [inline server/api/collections.js:470]: Could we return the file operation as `data` here? It would allow programmatically downloading the export once it's complete if the API consumer has the `id`

File: server/api/collections.js [hunk 5]
```diff
@@ -482,26 +478,26 @@ router.post("collections.export_all", auth(), async (ctx) => {
...
   authorize(user, "export", team);
 
-  await Event.create({
-    name: "collections.export",
-    teamId: user.teamId,
-    actorId: user.id,
-    ip: ctx.request.ip,
-  });
-
   if (download) {
```
Comment (tommoor) [inline server/api/collections.js:481]: Not sure it needs to be now but the plan will be to remove this flag entirely

File: server/api/fileOperations.js [hunk 6]
```diff
@@ -0,0 +1,83 @@
...
+import { FileOperation, User, Collection, Team } from "../models";
+import policy from "../policies";
+import { presentFileOperation } from "../presenters";
+import { getSignedUrl } from "../utils/s3";
+import pagination from "./middlewares/pagination";
+
+const { authorize } = policy;
+const router = new Router();
+
+router.post("fileOperations.list", auth(), pagination(), async (ctx) => {
```
Comment (tommoor) [inline server/api/fileOperations.js:14]: If we add a `fileOperations.info` it will allow polling the state of the export via the API, automating data export is actually a surprisingly common usecase so I do believe it would be used.

File: server/api/fileOperations.js [hunk 7]
```diff
@@ -0,0 +1,83 @@
...
+
+  const user = ctx.state.user;
+
+  const where = {
+    teamId: user.teamId,
+    type,
+  };
+
+  const team = await Team.findByPk(user.teamId);
+  authorize(user, type, team);
```
Comment (tommoor) [inline server/api/fileOperations.js:29]: `type` is coming directly from user input here, we're allowing them to choose what authorization they like :P 

Can use `ctx.assertIn(type, ["export", "import"], ...)` to ensure it's one of those two values instead of `assertPresent`

File: server/api/fileOperations.js [hunk 8]
```diff
@@ -0,0 +1,83 @@
...
+      ...ctx.state.pagination,
+      total,
+    },
+    data: exports.map(presentFileOperation),
+  };
+});
+
+router.post("fileOperations.redirect", auth(), async (ctx) => {
+  const { id } = ctx.body;
+  ctx.assertPresent(id, "id is required");
```
Comment (tommoor) [inline server/api/fileOperations.js:66]:
```suggestion
  ctx.assertUuid(id, "id is required");
```

Even more specific

File: server/api/fileOperations.js [hunk 9]
```diff
@@ -0,0 +1,83 @@
...
+
+  const user = ctx.state.user;
+  const team = await Team.findByPk(user.teamId);
+
+  const fileOp = await FileOperation.findByPk(id);
+  if (!fileOp) {
+    throw new NotFoundError();
+  }
+
```
Comment (tommoor) [inline server/api/fileOperations.js:75]: I think we can check if the fileOp.status !== complete and throw an error here

File: server/services/websockets.js [hunk 10]
```diff
@@ -327,6 +327,15 @@ export default class Websockets {
         }
         return;
       }
+
+      case "fileOperations.update": {
+        return socketio
+          .to(`user-${event.actorId}`)
+          .emit("fileOperations.update", {
+            ...event.data,
+          });
```
Comment (tommoor) [inline server/services/websockets.js:336]:
```suggestion
          .emit("fileOperations.update", event.data);
```

File: server/presenters/fileOperation.js [hunk 11]
```diff
@@ -0,0 +1,16 @@
...
+import { FileOperation } from "../models";
+import { presentCollection, presentUser } from ".";
+
+export default function present(data: FileOperation) {
+  return {
+    id: data.id,
+    type: data.type,
+    state: data.state,
+    collection: data.collection ? presentCollection(data.collection) : null,
+    key: data.key,
```
Comment (tommoor) [inline server/presenters/fileOperation.js:11]: Do we use `key`?  I think we can keep this private too

File: server/models/Event.js [hunk 12]
```diff
@@ -94,6 +95,7 @@ Event.AUDIT_EVENTS = [
   "documents.delete",
   "documents.permanent_delete",
   "documents.restore",
+  "fileOperations.update",
```
Comment (tommoor) [inline server/models/Event.js:98]:
```suggestion
```

No need, these won't be saved

File: server/emails/ExportSucessEmail.js [hunk 13]
```diff
@@ -8,25 +8,30 @@ import Footer from "./components/Footer";
...
+          Your requested data export is complete, the exported files are also
+          available in the admin section.
         </p>
         <EmptySpace height={10} />
         <p>
-          <Button href={`${process.env.URL}/home`}>Go to dashboard</Button>
+          <Button
+            href={`${process.env.URL}/api/fileOperations.redirect?id=${id}`}
+          >
+            View my export
```
Comment (tommoor) [inline server/emails/ExportSucessEmail.js:33]:
```suggestion
            Download
```

**Review by tommoor — CHANGES_REQUESTED** [review]
Getting late, I might have a couple more things but this is the bulk of my feedback~

As you mentioned this feature was a lot bigger than we both expected, glad you're able to power through it.

**Comment by iamsaumya** [comment]
Thanks for the review. I agree with all the points 👍🏻 .

> When triggering an individual collection export there is no feedback, maybe we should forward the user to /settings/import-export?

We send an email to the user when the export is ready. Redirecting them could lead to a scenario where the server already has a big queue to process, and the user will be staring at the progress of their export. At least, this is why I didn't propose to redirect them. What do you think?

**Comment by tommoor** [comment]
Sounds like a toast message is the way to go then, something like "Export started, you will receive an email when it’s complete"

**Comment by iamsaumya** [comment]
> * [ ]  Paragraph of text above "Export Data" button mentions emailing the zip, lets tweak that text to say that we'll email when the export is complete.

A full export might take some time, consider exporting a single document or collection if possible. The export data will be a zip of all your documents in Markdown format, and we’ll email a link to {{email}} when the export is complete.

Is this good?

**Comment by tommoor** [comment]
> A full export might take some time, consider exporting a single document or collection. The exported data is a zip of your documents in Markdown format. You may leave this page once the export has started – we will email a link to {{email}} when complete.

File: app/models/FileOperation.js (hunk 1 above)
Comment (iamsaumya) [reply app/models/FileOperation.js:18]: Noted. Earlier I neglected this, thinking collections would generally be greater than MB in production.

File: server/api/collections.js (hunk 5 above)
Comment (iamsaumya) [reply server/api/collections.js:481]: We are not using this in the app. I'm up for removing this. Is there something stopping us?

Comment (tommoor) [reply server/api/collections.js:481]: It might be in use by API consumers, but honestly the whole reason this exercise is happening is to avoid running large exports on the API process so lets remove :)

File: server/api/collections.js [hunk 14]
```diff
@@ -454,59 +455,64 @@ router.post("collections.export", auth(), async (ctx) => {
...
+      },
+    ],
   });
 
-  ctx.attachment(`${collection.name}.zip`);
-  ctx.set("Content-Type", "application/force-download");
-  ctx.body = fs.createReadStream(filePath);
+  ctx.body = {
+    success: true,
+    data: { fileOperation: presentFileOperation(exportData) },
```
Comment (iamsaumya) [inline server/api/collections.js:501]: Using fileOperation as key instead of not presenting it directly because the response is from a collection endpoint, and fileOperation is different model.

**Comment by iamsaumya** [comment]
> Listing "complete" here is actually a bit confusing when you didn't see the export process – there isn't a lot of context, I'm not sure if that means it should be removed so we only show status when it's incomplete, maybe?

I was giving this some thought because we mention a `complete` state of export in the messages stating we will send an email when it is reached. However, we are not showing the `Download` button until the complete state is reached. I think we can remove this tag when we reach `complete`.

**Comment by iamsaumya** [comment]
Checklist complete. Please review 😄

File: server/api/collections.js [hunk 15]
```diff
@@ -454,59 +455,64 @@ router.post("collections.export", auth(), async (ctx) => {
...
-  } else {
-    // async operation to create zip archive and email user
-    exportCollections(user.teamId, user.email);
-
-    ctx.body = {
-      success: true,
-    };
-  }
+  ctx.body = {
+    success: true,
```
Comment (tommoor) [inline server/api/collections.js:514]: Return `fileOperation` here the same as above?

File: server/api/fileOperations.js [hunk 16]
```diff
@@ -0,0 +1,123 @@
...
+  authorize(user, fileOperation.type, team);
+
+  if (!fileOperation) {
+    throw new NotFoundError();
+  }
+
+  ctx.body = {
+    data: presentFileOperation(fileOperation),
+  };
+});
```
Comment (tommoor) [inline server/api/fileOperations.js:44]:
```suggestion
});

```

File: server/api/fileOperations.js [hunk 17]
```diff
@@ -0,0 +1,123 @@
...
+
+  if (!fileOp) {
+    throw new NotFoundError();
+  }
+
+  if (fileOp.state !== "complete") {
+    throw new ValidationError("file operation is not complete yet");
+  }
+
+  authorize(user, fileOp.type, team);
```
Comment (tommoor) [inline server/api/fileOperations.js:116]: The `authorize` call here should come before the state check above otherwise we're leaking the state of internal system to an unauthorized user

File: server/api/fileOperations.js [hunk 18]
```diff
@@ -0,0 +1,123 @@
...
+        model: User,
+        as: "user",
+        paranoid: false,
+      },
+      {
+        model: Collection,
+        as: "collection",
+        paranoid: false,
+      },
+    ],
```
Comment (tommoor) [inline server/api/fileOperations.js:32]: Seems like this is repeated a lot, we can use sequelize's `defaultScope` in the model to make sure they are always included and remove this include statement in several places

File: server/migrations/20210730210120-add-fileOperations.js [hunk 19]
```diff
@@ -0,0 +1,65 @@
...
+      createdAt: {
+        type: Sequelize.DATE,
+        allowNull: false,
+      },
+      updatedAt: {
+        type: Sequelize.DATE,
+        allowNull: false,
+      },
+    })
+    await queryInterface.addIndex('file_operations', ["state","type"]);
```
Comment (tommoor) [inline server/migrations/20210730210120-add-fileOperations.js:58]: This adds a single compound-index which would require "state" to be in the query, I don't think that's what you meant to do?

```suggestion
    await queryInterface.addIndex('file_operations', ["state"]);
    await queryInterface.addIndex('file_operations', ["type"]);
```

If not `removeIndex` below will also need changing

File: server/migrations/20210730210120-add-fileOperations.js [hunk 20]
```diff
@@ -0,0 +1,65 @@
...
+  },
+
+  down: async (queryInterface, Sequelize) => {
+    await queryInterface.removeIndex('file_operations', ["state","type"]);
```
Comment (tommoor) [inline server/migrations/20210730210120-add-fileOperations.js:62]:
```suggestion
    await queryInterface.removeIndex('file_operations', ["state"]);
    await queryInterface.removeIndex('file_operations', ["type"]);
```

File: server/emails/ExportFailureEmail.js [hunk 21]
```diff
@@ -0,0 +1,40 @@
...
+
+      <Body>
+        <Heading>Your Data Export</Heading>
+        <p>
+          Sorry, your requested data export has failed, please visit the export
+          section to try again – if the problem persists please contact support.
+        </p>
+        <EmptySpace height={10} />
+        <p>
+          <Button href={`${process.env.URL}/settings/import-export`}>
```
Comment (tommoor) [inline server/emails/ExportFailureEmail.js:31]: We need to pass `teamUrl` and use it here (same as welcome email) instead of the `process.env.URL` otherwise on cloud hosted it will send them to `https://app.getoutline.com/settings/ where they won't be signed in.

File: server/emails/ExportSucessEmail.js [hunk 22]
```diff
@@ -8,25 +8,30 @@ import Footer from "./components/Footer";
...
         <Heading>Your Data Export</Heading>
         <p>
-          Your requested data export is attached as a zip file to this email.
+          Your requested data export is complete, the exported files are also
+          available in the admin section.
         </p>
         <EmptySpace height={10} />
         <p>
-          <Button href={`${process.env.URL}/home`}>Go to dashboard</Button>
+          <Button
```
Comment (tommoor) [inline server/emails/ExportSucessEmail.js:30]: We need to pass `teamUrl` and use it here (same as welcome email)  instead of the `process.env.URL` otherwise on cloud hosted it will send them to `https://app.getoutline.com/api/... where they won't be signed in.

File: server/mailer.js [hunk 23]
```diff
@@ -14,7 +14,15 @@ import {
...
-import { ExportEmail, exportEmailText } from "./emails/ExportEmail";
+import {
+  ExportFailureEmail,
+  exportEmailFailureText,
+} from "./emails/ExportFailureEmail";
+
+import {
+  ExportSuccessEmail,
+  exportEmailSuccessText,
+} from "./emails/ExportSucessEmail";
```
Comment (tommoor) [inline server/mailer.js:25]: "Success" is spelt wrong in this filename, seems okay elsewhere

File: server/emails/ExportSucessEmail.js [hunk 24]
```diff
@@ -8,25 +8,30 @@ import Footer from "./components/Footer";
...
   return (
     <EmailTemplate>
       <Header />
 
       <Body>
         <Heading>Your Data Export</Heading>
         <p>
-          Your requested data export is attached as a zip file to this email.
+          Your requested data export is complete, the exported files are also
+          available in the admin section.
```
Comment (tommoor) [inline server/emails/ExportSucessEmail.js:26]: We should link "admin section"?

File: server/emails/ExportSucessEmail.js [hunk 25]
```diff
@@ -8,25 +8,30 @@ import Footer from "./components/Footer";
 import Header from "./components/Header";
 import Heading from "./components/Heading";
 
-export const exportEmailText = `
+export const exportEmailSuccessText = `
 Your Data Export
 
-Your requested data export is attached as a zip file to this email.
+Your requested data export is complete, the exported files are also available in the admin section.
```
Comment (tommoor) [inline server/emails/ExportSucessEmail.js:14]: Add a link to "admin section" below otherwise this text email is a dead end.

File: server/emails/ExportFailureEmail.js [hunk 26]
```diff
@@ -0,0 +1,40 @@
...
+import EmptySpace from "./components/EmptySpace";
+import Footer from "./components/Footer";
+import Header from "./components/Header";
+import Heading from "./components/Heading";
+
+export const exportEmailFailureText = `
+Your Data Export
+
+Sorry, your requested data export has failed, please visit the export
+section to try again – if the problem persists please contact support.
```
Comment (tommoor) [inline server/emails/ExportFailureEmail.js:15]: Add a link to "admin section" below otherwise this text email is a dead end.

File: server/emails/ExportFailureEmail.js [hunk 27]
```diff
@@ -0,0 +1,40 @@
...
+
+export const ExportFailureEmail = () => {
+  return (
+    <EmailTemplate>
+      <Header />
+
+      <Body>
+        <Heading>Your Data Export</Heading>
+        <p>
+          Sorry, your requested data export has failed, please visit the export
```
Comment (tommoor) [inline server/emails/ExportFailureEmail.js:26]:
```suggestion
          Sorry, your requested data export has failed, please visit the admin
```

File: server/emails/ExportFailureEmail.js [hunk 28]
```diff
@@ -0,0 +1,40 @@
...
+import EmailTemplate from "./components/EmailLayout";
+import EmptySpace from "./components/EmptySpace";
+import Footer from "./components/Footer";
+import Header from "./components/Header";
+import Heading from "./components/Heading";
+
+export const exportEmailFailureText = `
+Your Data Export
+
+Sorry, your requested data export has failed, please visit the export
```
Comment (tommoor) [inline server/emails/ExportFailureEmail.js:14]:
```suggestion
Sorry, your requested data export has failed, please visit the admin
```

File: server/exporter.js [hunk 29]
```diff
@@ -15,45 +19,188 @@ const queueOptions = {
...
+    collections = [await Collection.findByPk(collectionId)];
+  }
+
+  const acl = process.env.AWS_S3_ACL || "private";
+
+  let exportData;
+  let state;
+  let key;
+
+  if (fileOperationId) {
```
Comment (tommoor) [inline server/exporter.js:83]: I'm trying to follow why in one case the fileOperationId is created outside and passed in, but in the other it's inside of this method, are you able to explain?

Overall everything works well but this method feels "messy"

File: server/exporter.js [hunk 30]
```diff
@@ -15,45 +19,188 @@ const queueOptions = {
...
   const team = await Team.findByPk(teamId);
-  const collections = await Collection.findAll({
-    where: { teamId },
-    order: [["name", "ASC"]],
-  });
+  const user = await User.findByPk(userId);
+
+  let collections;
+  if (!collectionId) {
+    collections = await Collection.scope({
```
Comment (tommoor) [inline server/exporter.js:60]: There is a convenience method for this, `await user.collectionIds();`, that calculates all of the permissions. So could grab the id's and then query collections with id in that list.

**Review by tommoor — CHANGES_REQUESTED** [review]
I'm sorry the feedback is never ending on this one

File: app/stores/FileOperationsStore.js [hunk 31]
```diff
@@ -0,0 +1,27 @@
...
+  @computed
+  get exports(): FileOperation[] {
+    return Array.from(this.data.values()).reduce(
+      (acc, fileOp) => (fileOp.type === "export" ? [...acc, fileOp] : acc),
+      []
+    );
+  }
+
+  @computed
+  get orderedDataExports(): FileOperation[] {
```
[the remark this answers is not in the document]
Comment (iamsaumya) [reply app/stores/FileOperationsStore.js:24]: I named it so believing in future we will need an `orderedData` for `import` as well.

File: server/api/collections.js [hunk 32]
```diff
@@ -454,59 +455,64 @@ router.post("collections.export", auth(), async (ctx) => {
...
-    collectionId: collection.id,
-    teamId: user.teamId,
-    actorId: user.id,
-    data: { title: collection.title },
-    ip: ctx.request.ip,
+  const name = collection ? collection.name : team.name;
+  const acl = process.env.AWS_S3_ACL || "private";
+  const key = getAWSKeyForFileOp(team.id, name, acl);
+
+  let exportData;
```
[the remark this answers is not in the document]
Comment (iamsaumya) [reply server/api/collections.js:472]: the `fileOperation` is of export type, maybe `exportFileOperation`?

File: server/exporter.js (hunk 29 above)
Comment (iamsaumya) [reply server/exporter.js]: Modified both the endpoints to create fileOperation before putting tasks on the queue

File: server/migrations/20210730210120-add-fileOperations.js (hunk 19 above)
Comment (iamsaumya) [reply server/migrations/20210730210120-add-fileOperations.js:58]: We use `type` and `state` attributes while querying. I thought a compound index would be must faster than having a single index.

Suppose we are not going with compound indexes. I think the `type` index is all that we need.  

```    
where: {
  type: "export",
  createdAt: {
    [Op.lt]: subDays(new Date(), 30),
  },
  state: {
    [Op.ne]: "expired",
  },
 },
 ```

Comment (iamsaumya) [reply server/migrations/20210730210120-add-fileOperations.js:58]: Noted.

**Review by tommoor — APPROVED** [review]

**Comment by tommoor** [comment]
I think there is a follow up here to refactor the exporter to use the command pattern, it should clean things up quite a lot. But this was needed prior to this work so it's in no way a requirement for the PR.

**Comment by iamsaumya** [comment]
Doing the merge 🤞🏻
