### PR TITLE
fix: Multiple fixes to sticky headers on tables

### LINKED ISSUE #11477: Broken table sticky headers during scroll
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This is not related to configuring Outline

- [x] The issue is not related to self-hosting config

### Current Behavior

Bug Demo:

https://github.com/user-attachments/assets/7dc2e797-d827-4847-894d-2b51ffdab321

Approximately two days ago everything work fine.

### Expected Behavior

_No response_

### Steps To Reproduce

1. create big table with merged cells
2. scroll table

### Environment

```markdown
- Outline: latest cloud version
- Browser: Chrome 144.0.7559.59 (Official Build) (arm64)
- OS: macos 26.2 (25C56)
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by tommoor**
- Custom header color incorrect text color
- Header column sticky unnecessarily
- Incorrect text color used on header with custom background 
- Header with custom background showing content behind when sticky 

closes #11477

### CODE REVIEW

File: shared/editor/components/Styles.ts [hunk 1]
```diff
@@ -1954,8 +1954,10 @@ table {
     padding: 4px 0;
   }
 
-  td[data-bgcolor] {
+  td[data-bgcolor],
+  th[data-bgcolor] {
     color: var(--cell-text-color);
+    background: linear-gradient(var(--cell-bg-color), var(--cell-bg-color)), linear-gradient(${props.theme.background}, ${props.theme.background});
```
Comment (tommoor) [inline shared/editor/components/Styles.ts:1960]: We use gradients here to achieve multiple layered backgrounds that are not possible with solid colors.
