### PR TITLE
Fixes exception visiting doc unauthenticated

### LINKED ISSUE #480: Visiting document pages unauthenticated leads to an exception
Was looking through exceptions and visiting a document URL while being logged out leads to an exception. Redirect to marketing page still works tho.

### PR DESCRIPTION
**Pull request by tommoor**
Also pulled the `Auth` component out into it's own file for legibility, that index.js is getting big.

Closes #480

### CODE REVIEW

File: app/components/Auth.js [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+      stores.auth.fetch();
+      authenticatedStores.collections.fetchAll();
+    }
+
+    return <Provider {...authenticatedStores}>{children}</Provider>;
+  }
+
+  stores.auth.logout();
+  window.location.href = BASE_URL;
+  return null;
```
Comment (tommoor) [inline app/components/Auth.js]: This is the actual fix. Even though we redirect the component has to return a valid React node.
