### PR TITLE
fix: Show diff from document when revision has not been created yet

### LINKED ISSUE #8403: Revision entry sometimes show wrong diff
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This is not related to configuring Outline

- [x] The issue is not related to self-hosting config

### Current Behavior

Sometimes, clicking on a fresh revision in the History page shows diffs from a prior change.

### Expected Behavior

_No response_

### Steps To Reproduce

1. Make a simple word insertion to a doc.
2. Wait for idle, until status says "You updated less than a minute ago"
3. `...` > History
4. Click on the latest (topmost) entry. The diff is wrong ❌ 
5. Click on the second latest entry, and then back to the latest entry. It's correct now ✔ 

### Environment

```markdown
`ac487671`
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by hmacr**
Closes #8403 

Also fixes the spurious revision shown as the latest when any non-revision events like delete, unpublish happens.

### CODE REVIEW

File: app/scenes/Document/components/History.tsx [hunk 1]
```diff
@@ -136,14 +136,19 @@ function History() {
...
+    if (latestRevisionEvent && document) {
+      const latestRevision = revisions.get(latestRevisionEvent.id);
 
-    if (latestEvent && document) {
-      const latestRevisionEvent = merged.find(
-        (event) => event.name === "revisions.create"
-      );
+      const isDocUpdated =
+        latestRevision?.title !== document.title ||
+        JSON.stringify(latestRevision.data) !== JSON.stringify(document.data);
```
Comment (tommoor) [inline app/scenes/Document/components/History.tsx:148]: Do we need to stringify? Might it be faster to use `isEqual` is it can bail as soon as an inequality is found

Comment (hmacr) [reply app/scenes/Document/components/History.tsx:148]: yes, `fast-deep-equal` totally slipped my mind.

**Review by tommoor — APPROVED** [review]
