### PR TITLE
fix: Remove star option on publicly shared docs

### LINKED ISSUE #2803: Remove star from document headings on shared documents
Currently the option to star appears in headings on shared documents when signed in with permission. This is a bit strange, we should keep the separation between public/private here and not show the star.

### PR DESCRIPTION
**Pull request by tommoor**
closes #2803

### CODE REVIEW

File: app/scenes/Document/components/EditableTitle.tsx [hunk 1]
```diff
@@ -15,9 +15,15 @@ import { isModKey } from "~/utils/keyboard";
 type Props = {
   value: string;
   document: Document;
+  /** Should the title be editable, policies will also be considered separately */
```
Comment (tommoor) [inline app/scenes/Document/components/EditableTitle.tsx:18]: These comments show up when you use the component, so that's pretty nice. We should make more use of this going forward!
