### PR TITLE
fix: Clickable area for docs in sidebar is obstructed

### LINKED ISSUE #2808: Clickable area for docs in sidebar is obstructed
Looks like the `DropCursor` component is in the way

### PR DESCRIPTION
**Pull request by tommoor**
Also simplifies the logic for collapsing collections when dragging by avoiding sending state out to the parent component and relying on the `useDrop` `monitor` instead.

This is so much nicer now, no "dead" areas in the sidebar when hovering over docs in manually sorted collections.

closes #2808

### CODE REVIEW

File: app/components/Sidebar/components/DocumentLink.tsx [hunk 1]
```diff
@@ -275,7 +276,7 @@ function DocumentLink(
             </DropToImport>
           </div>
         </Draggable>
-        {manualSort && (
+        {manualSort && isDraggingAnyDocument && (
```
Comment (tommoor) [inline app/components/Sidebar/components/DocumentLink.tsx:279]: Don't render the cursor unless we're drag-n-dropping'

Note: We were already doing this for collections!
