### PR TITLE
fix: Multiplayer changes potentially attributed to incorrect user

### LINKED ISSUE #4267: Document changes attributed to wrong user
Document changes on the History tab are attributed to a user that's not the author of the change.

**To Reproduce**
1. Open a document and do some changes
2. Have a collaborator be on the document with you clicking randomly but not writing anything
3. Abandon the document.
4. See that the history is incorrect and the email notifications quote the wrong person.

**Expected behavior**
That the changes that are highlighted on the History are attributed to the person making the change

**Screenshots**
imagen

**Outline (please complete the following information):**
- Install: getoutline.com
- Version: ?

**Desktop (please complete the following information):**
 - OS: Windows
 - Chrome 105 and Firefox 105

### PR DESCRIPTION
**Pull request by tommoor**
Also performance improvements in collaboration persistence.

closes #4267

### CODE REVIEW

File: server/commands/documentCollaborativeUpdater.ts [hunk 1]
```diff
@@ -18,7 +19,10 @@ export default async function documentCollaborativeUpdater({
   return sequelize.transaction(async (transaction) => {
     const document = await Document.unscoped()
       .scope("withState")
-      .findByPk(documentId, {
+      .findOne({
```
Comment (tommoor) [inline server/commands/documentCollaborativeUpdater.ts:22]: This change makes a big difference – `findByPk` overrides the scope and ignores our `"withState"` scope 😢 – this means that we've been writing the full state to disk on every persistence event. Should improve database load considerably.
