### PR TITLE
fix: YouTube `referrerpolicy` requirements seem to have tightened

### LINKED ISSUE #10502: Some YouTube embeds stopped working
Seems related to referrerPolicy

### PR DESCRIPTION
**Pull request by tommoor**
closes #10502

### CODE REVIEW

File: shared/editor/embeds/YouTube.tsx [hunk 1]
```diff
@@ -28,7 +31,15 @@ function YouTube({ matches, ...props }: Props) {
...
+      referrerPolicy="strict-origin-when-cross-origin"
+      src={src}
+      title={`YouTube (${videoId})`}
+      ref={ref}
+    />
+  );
 }
 
-export default YouTube;
+export default React.forwardRef(YouTube);
```
Comment (tommoor) [inline shared/editor/embeds/YouTube.tsx:45]: Unrelated, but this was causing warnings
