### PR TITLE
fix: Use friendly urls for collections

### LINKED ISSUE #1995: Use friendly urls for collections
We've been storing `urlId` in the database for collections since day 1, in the same way we do for documents – but we've never used it! It should be relatively simple to update the `findByPk` method to accept a urlId (basically copy and paste from the Document one) and then have the frontend use them.

This way we change urls from:

`https://app.getoutline.com/collections/8e6edb23-e4b7-474c-97b4-5e7fec49df56` ->
`https://app.getoutline.com/collections/product-97b4ih`

### PR DESCRIPTION
**Pull request by iamsaumya**
Closes #1995

Todos
- [x] Expose collection urlId to frontend
- [x] Update URL getterMethods to return new URL type
- [x] Update findByPk(similar to doc)
- [x] Add getByUrl in collection store
- [x] Add useEffect to redirect to new URL type
- [x] Overried fetch in collection store
- [x] fix bug, to return null when the urlId and slugified name do match to a collection.
- [x] Migrate from /collections/ to /collection/

### CODE REVIEW

File: app/stores/BaseStore.js [hunk 1]
```diff
@@ -140,6 +140,11 @@ export default class BaseStore<T: BaseModel> {
     }
 
     let item = this.data.get(id);
+
+    if (this.modelName === "Collection") {
+      item = this.rootStore.collections.getByUrl(id);
+    }
+
```
Comment (iamsaumya) [inline app/stores/BaseStore.js:147]: @tommoor, Is this okay, or Should I consider creating fetch in the collection store?

File: server/models/Collection.js [hunk 2]
```diff
@@ -223,6 +226,17 @@ Collection.addHook("afterCreate", (model: Collection, options) => {
 
 // Class methods
 
+Collection.findByPk = async function (id, options = {}) {
+  if (isUUID(id)) {
+    return this.findOne({ where: { id }, ...options });
```
Comment (iamsaumya) [inline server/models/Collection.js:231]: We are using `findByPk` with two `scopes`. So I used `this` here. All the server test cases are passing, so I think `this` is using the scope returned by the `scopes`.

File: app/stores/BaseStore.js (hunk 1 above)
Comment (tommoor) [reply app/stores/BaseStore.js:147]: Override fetch in collection store pls :) This feature is likely to mean a bit of copy/paste from documents but that's okay.

**Comment by iamsaumya** [comment]
This looks good to me. Please give it a review whenever you're unoccupied to help me corner cases.

File: app/stores/CollectionsStore.js [hunk 3]
```diff
@@ -135,6 +159,12 @@ export default class CollectionsStore extends BaseStore<Collection> {
     if (path) return path.title;
   }
 
+  getByUrl(url: string): ?Collection {
+    return find(Array.from(this.data.values()), (col: Collection) =>
```
Comment (tommoor) [inline app/stores/CollectionsStore.js:163]:
```suggestion
    return find(this.orderedData, (col: Collection) =>
```

`orderedData` is already a pre-computed array we can use here

File: app/scenes/Collection.js [hunk 4]
```diff
@@ -38,18 +48,31 @@ import { newDocumentUrl, collectionUrl } from "utils/routeHelpers";
...
+  const collection = collections.getByUrl(id);
+  const can = policies.abilities(collection?.id || "");
   const canUser = policies.abilities(team.id);
-  const { handleFiles, isImporting } = useImportDocument(collectionId);
+  const { handleFiles, isImporting } = useImportDocument(collection?.id || "");
+
+  React.useEffect(() => {
+    async function load() {
+      if (isUUID(id)) {
+        const collection = await collections.fetch(id);
```
Comment (tommoor) [inline app/scenes/Collection.js:69]: The `collection` model is already guaranteed to be fetched for this screen, I wonder if we could we just add `collection` as a dependency of useEffect and wait for it to exist?

File: app/scenes/Collection.js [hunk 5]
```diff
@@ -38,18 +48,31 @@ import { newDocumentUrl, collectionUrl } from "utils/routeHelpers";
...
   const team = useCurrentTeam();
   const [isFetching, setFetching] = React.useState();
   const [error, setError] = React.useState();
   const [permissionsModalOpen, setPermissionsModalOpen] = React.useState(false);
 
-  const collectionId = params.id || "";
-  const collection = collections.get(collectionId);
-  const can = policies.abilities(collectionId || "");
+  const id = params.id || "";
+  const collection = collections.getByUrl(id);
```
Comment (tommoor) [inline app/scenes/Collection.js:61]:
```suggestion
  const collection = collections.getByUrl(id) || collections.get(id);
```

Would it be useful for backwards compat and avoid the extra fetch call when loading an old-style url?

File: app/scenes/DocumentNew.js [hunk 6]
```diff
@@ -1,58 +1,52 @@
...
-    } catch (err) {
-      this.props.ui.showToast("Couldn’t create the document, try again?", {
-        type: "error",
-      });
-      this.props.history.goBack();
+  useEffect(() => {
+    async function createDocument() {
+      const params = queryString.parse(location.search);
+      try {
+        const collection = await collections.fetch(match.params.id || "");
```
Comment (tommoor) [inline app/scenes/DocumentNew.js:23]: We should be able to make the fetch here a fallback if collection can't be found in the store, 99.9% of the time the collection will be loaded locally already

File: server/models/Collection.js (hunk 2 above)
Comment (tommoor) [reply server/models/Collection.js:231]: This makes sense, a couple of explicit tests for the cases of passing a uuid / urlId here  would be good.

File: server/models/Collection.js [hunk 7]
```diff
@@ -1,12 +1,13 @@
...
 import randomstring from "randomstring";
-import slug from "slug";
+import isUUID from "validator/lib/isUUID";
 import { Op, DataTypes, sequelize } from "../sequelize";
+import slugify from "../utils/slugify";
 import CollectionUser from "./CollectionUser";
 import Document from "./Document";
 
-slug.defaults.mode = "rfc3986";
+const URL_REGEX = /^[0-9a-zA-Z-_~]*-([a-zA-Z0-9]{10,15})$/;
```
Comment (tommoor) [inline server/models/Collection.js:10]: I wonder if we should centralize this now it's used in two places, perhaps export from shared/routeHelpers?

File: app/utils/routeHelpers.js [hunk 8]
```diff
@@ -14,10 +14,19 @@ export function newCollectionUrl(): string {
...
-export function collectionUrl(collectionId: string, section: ?string): string {
-  const path = `/collections/${collectionId}`;
-  if (section) return `${path}/${section}`;
-  return path;
+export function collectionUrl(url: string, section: ?string): string {
+  if (section) return `${url}/${section}`;
+  return url;
+}
+
+export function updateCollectionUrl(oldUrl: string, newUrl: string): string {
```
Comment (tommoor) [inline app/utils/routeHelpers.js:22]: Wondering if this would be more maintainable as a string replacement, looking for `collections/${collection.id}` -> `collections.url` ?

File: server/models/Collection.js (hunk 2 above)
Comment (iamsaumya) [reply server/models/Collection.js:231]: Agree, Will do that.

File: app/scenes/DocumentNew.js (hunk 6 above)
Comment (iamsaumya) [reply app/scenes/DocumentNew.js:23]: We do `collection.get` and `collections.getByUrl` calls inside the fetch.

File: app/utils/routeHelpers.js (hunk 8 above)
Comment (iamsaumya) [reply app/utils/routeHelpers.js:22]: I am sorry I didn't get it. Isn't this what we are doing?

Comment (tommoor) [reply app/utils/routeHelpers.js:22]: I think that's what this is achieving but in a slightly more fragile way by splitting and recombining the parts. Could it not be?

```javascript
  return oldUrl.replace(`collections/${collection.id}`, collections.url);
```

**Review by tommoor — COMMENTED** [review]
Working great while testing locally, haven't found an edgecase yet

**Comment by tommoor** [comment]
Now that I see it in the url I'm thinking it would make sense to take this opportunity to singularize the new routes to "collection" the same as "doc"

**Comment by iamsaumya** [comment]
I would be happy to make another PR with those changes. It will help us keep this PR focused on collections.

File: app/utils/routeHelpers.js (hunk 8 above)
Comment (iamsaumya) [reply app/utils/routeHelpers.js:22]: Do you suggest modify the `updateDocumentUrl`? This function is an exact copy of it, and just the name is different 😅

File: app/scenes/DocumentNew.js [hunk 9]
```diff
@@ -1,58 +1,52 @@
...
+          collectionId: collection.id,
+          parentDocumentId: params.parentDocumentId,
+          templateId: params.templateId,
+          template: params.template,
+          title: "",
+          text: "",
+        });
+        history.replace(editDocumentUrl(document));
+      } catch (err) {
+        ui.showToast("Couldn’t create the document, try again?", {
```
[the remark this answers is not in the document]
Comment (iamsaumya) [reply app/scenes/DocumentNew.js:34]: Thanks for pointing out 👍🏻

File: app/utils/routeHelpers.js (hunk 8 above)
Comment (tommoor) [reply app/utils/routeHelpers.js:22]: Hah, maybe! My old code can always be improved... but maybe I'm missing something here, it's late

Comment (iamsaumya) [reply app/utils/routeHelpers.js:22]: I will update it if it doesn't break anything.

File: app/routes/authenticated.js [hunk 10]
```diff
@@ -46,9 +46,9 @@ export default function AuthenticatedRoutes() {
           <Route exact path="/drafts" component={Drafts} />
           <Route exact path="/archive" component={Archive} />
           <Route exact path="/trash" component={Trash} />
-          <Route exact path="/collections/:id/new" component={DocumentNew} />
-          <Route exact path="/collections/:id/:tab" component={Collection} />
-          <Route exact path="/collections/:id" component={Collection} />
```
Comment (tommoor) [inline app/routes/authenticated.js:51]: We'll need to retain a redirect from `/collections/*` -> `/collection/*` here

File: app/scenes/DocumentNew.js [hunk 11]
```diff
@@ -1,58 +1,60 @@
...
-  async componentDidMount() {
-    const params = queryString.parse(this.props.location.search);
+  useEffect(() => {
+    async function createDocument() {
+      const params = queryString.parse(location.search);
+      try {
+        const collection =
+          collections.getByUrl(id) ||
+          collections.get(id) ||
+          (await collections.fetch(id));
```
Comment (tommoor) [inline app/scenes/DocumentNew.js:29]:
```suggestion
        const collection = await collections.fetch(id);
```

Checking for id is part of `fetch`, right? No need for these extra checks

File: server/models/Collection.test.js [hunk 12]
```diff
@@ -416,3 +418,63 @@ describe("#membershipUserIds", () => {
     expect(membershipUserIds.length).toBe(6);
   });
 });
+
+describe("#findByPk", () => {
+  test("should return collection with collection Id", async () => {
+    const { collection } = await seed();
```
Comment (tommoor) [inline server/models/Collection.test.js:424]:
```suggestion
    const collection = await buildCollection();
```

`seed` is quite slow as it builds a bunch of different models, I'm trying to avoid using it in new tests in favor of individual factories like above

File: server/models/Collection.test.js [hunk 13]
```diff
@@ -416,3 +418,63 @@ describe("#membershipUserIds", () => {
...
+  });
+
+  test("should return null when urlId is present but corresponding collection name is incorrect", async () => {
+    const { collection } = await seed();
+    const id = `${slugify("not present collection")}-${collection.urlId}`;
+
+    const response = await Collection.findByPk(id);
+
+    expect(response).toBe(null);
+  });
```
Comment (tommoor) [inline server/models/Collection.test.js:479]: Hmm, this is unexpected behavior – as long as the `urlId` is correct the slug portion can be anything. This enables the title to be changed and existing links that might exist to continue working

File: server/models/Document.js [hunk 14]
```diff
@@ -217,12 +217,16 @@ Document.findByPk = async function (id, options = {}) {
...
       where: {
-        urlId: id.match(URL_REGEX)[1],
+        urlId: id.match(URL_REGEX)[2],
       },
       ...options,
     });
+    if (document && slugify(document.title) !== id.match(URL_REGEX)[1]) {
+      return null;
+    }
+    return document;
```
Comment (tommoor) [inline server/models/Document.js:229]: See comment on test, this addition is undesired

File: app/scenes/Collection.js [hunk 15]
```diff
@@ -38,18 +49,28 @@ import { newDocumentUrl, collectionUrl } from "utils/routeHelpers";
...
+  const id = params.id || "";
+  const collection: ?Collection =
+    collections.getByUrl(id) || collections.get(id);
+  const can = policies.abilities(collection?.id || "");
   const canUser = policies.abilities(team.id);
-  const { handleFiles, isImporting } = useImportDocument(collectionId);
+  const { handleFiles, isImporting } = useImportDocument(collection?.id || "");
+
+  React.useEffect(() => {
+    if (isUUID(id) && collection) {
```
Comment (tommoor) [inline app/scenes/Collection.js:69]: Rather than checking `isUUID` here we should check if the current url !== canonicalUrl and redirect in that instance, this allows for old slugs to be updated if, for example, there is an external link somewhere to a collection that gets renamed.

(This is the same pattern used on documents)

File: shared/utils/routeHelpers.js [hunk 16]
```diff
@@ -61,3 +61,5 @@ export function settings(): string {
 export function groupSettings(): string {
   return `/settings/groups`;
 }
+
+export const URL_REGEX = /^([0-9a-zA-Z-_~]*)-([a-zA-Z0-9]{10,15})$/;
```
Comment (tommoor) [inline shared/utils/routeHelpers.js:65]:
```suggestion
export const SLUG_URL_REGEX = /^([0-9a-zA-Z-_~]*)-([a-zA-Z0-9]{10,15})$/;
```

Might be clearer in the future now it's no longer within the context of documents specifically.

**Review by tommoor — CHANGES_REQUESTED** [review]

File: server/models/Collection.test.js (hunk 12 above)
Comment (iamsaumya) [reply server/models/Collection.test.js:424]: Oh! For some reason, I thought seed should be fast 😅

File: server/models/Collection.test.js (hunk 13 above)
Comment (iamsaumya) [reply server/models/Collection.test.js:479]: Noted. 👍🏻

File: app/utils/routeHelpers.js [hunk 17]
```diff
@@ -25,7 +25,10 @@ export function updateCollectionUrl(
   collection: Collection
 ): string {
   // Update url to match the current one
-  return oldUrl.replace(`/collection/${collection.id}`, collection.url);
```
Comment (iamsaumya) [inline app/utils/routeHelpers.js]: This approach was not updating the URL if it is `wrong-collection-r9QsabjdGv` to `correct-collection-r9QsabjdGv`.

Comment (tommoor) [reply app/utils/routeHelpers.js]: aha!

**Review by tommoor — APPROVED** [review]
I think this is ready to go
