### PR TITLE
fix: Scroll does not reset when navigating shared docs on mobile

### LINKED ISSUE #6968: Scroll does not reset when navigating between publicly shared pages on mobile
**To Reproduce**
1. Go to a publicly shared document
2. Scroll down
3. Navigate to another
4. Scroll is not reset

### PR DESCRIPTION
**Pull request by tommoor**
closes #6968

### CODE REVIEW

File: app/components/ScrollToTop.ts [hunk 1]
```diff
@@ -25,8 +27,9 @@ export default function ScrollToTop({ children }: Props) {
     ) {
       return;
     }
-    window.scrollTo(0, 0);
+    (scrollContainerRef?.current || window).scrollTo(0, 0);
```
Comment (tommoor) [inline app/components/ScrollToTop.ts:30]: The problem was this hardcoded to resetting `window` scroll, but on mobile we're in a wrapper.
