### PR TITLE
fix: Embed disabled state should persist

### LINKED ISSUE #3001: Locally persist "Disable Embeds" per document
I tick the Disable Embeds option, but after refreshing the page, the embeds return back. The embeds are very annoying.

### PR DESCRIPTION
**Pull request by tommoor**
Also normalizes `localStorage` access to a `Storage` class.

closes #3001

### CODE REVIEW

File: app/models/Document.ts [hunk 1]
```diff
@@ -18,11 +19,28 @@ type SaveOptions = {
...
 
 export default class Document extends ParanoidModel {
+  constructor(fields: Record<string, any>, store: DocumentsStore) {
+    super(fields, store);
+
+    if (this.isPersistedOnce && this.isFromTemplate) {
+      this.title = "";
+    }
+
+    this.embedsDisabled = Storage.get(`embedsDisabled-${this.id}`) ?? false;
```
Comment (tommoor) [inline app/models/Document.ts:29]: I hate this, will try and move to a decorator.
