### PR TITLE
fix: Add ability to choose user permission level when inviting

### LINKED ISSUE #2113: Add ability to choose user permission level when inviting
It would be nice if we offered a dropdown when inviting a user to choose if they should have "view-only" permissions now this is a feature, the server model should support this without issue however the API will need to get the parameter added for when creating invites.

### PR DESCRIPTION
**Pull request by iamsaumya**
Closes #2113

### CODE REVIEW

File: app/scenes/Invite.js [hunk 1]
```diff
@@ -26,15 +27,16 @@ type Props = {|
 type InviteRequest = {
   email: string,
   name: string,
+  role: string,
```
Comment (tommoor) [inline app/scenes/Invite.js:30]:
```suggestion
  role: "member" | "viewer" | "admin",
```

lets type this a little more strictly, there's a few spots in this PR

File: app/scenes/Settings/components/UserInviteMenu.js [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+      />
+    </Wrapper>
+  );
+};
+
+const Wrapper = styled(Flex)`
+  margin: 0px;
+  position: relative;
+  flex-shrink: unset;
+  top: ${(props) => (props.setTop ? "28px" : "0")};
```
Comment (tommoor) [inline app/scenes/Settings/components/UserInviteMenu.js:50]: I think using the select input will help avoid this odd api

File: app/scenes/Settings/components/UserInviteMenu.js [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+        key: "admin",
+        label: t("Admin"),
+      },
+    ],
+    [t]
+  );
+
+  return (
+    <Wrapper setTop={setTop}>
+      <FilterOptions
```
Comment (tommoor) [inline app/scenes/Settings/components/UserInviteMenu.js:36]: Can we use the select input component for this?

File: server/commands/userInviter.js [hunk 4]
```diff
@@ -52,6 +52,8 @@ export default async function userInviter({
       name: invite.name,
       email: invite.email,
       service: null,
+      isAdmin: invite.role === "admin",
```
Comment (tommoor) [inline server/commands/userInviter.js:55]: We need to check the `inviteUser` policy in this api method to ensure only admins can invite.

Looks like this was an existing bug which was bad, but with the ability to create admins it would become a privilege escalation issue.

File: app/scenes/Settings/components/UserInviteMenu.js [hunk 5]
```diff
@@ -0,0 +1,53 @@
...
+import FilterOptions from "components/FilterOptions";
+import Flex from "components/Flex";
+
+type Props = {|
+  activeKey: string,
+  onSelect: (key: ?string) => void,
+  setTop: boolean,
+|};
+
+const UserInviteMenu = ({ activeKey, onSelect, setTop }: Props) => {
```
Comment (tommoor) [inline app/scenes/Settings/components/UserInviteMenu.js:14]: Maybe `InputSelectRole`, see `InputSelectPermission` as an example

**Review by tommoor — CHANGES_REQUESTED** [review]
Great start, it works

File: app/scenes/Invite.js [hunk 6]
```diff
@@ -182,7 +192,13 @@ function Invite({ onSubmit }: Props) {
...
             value={invite.name}
             required={!!invite.email}
-            flex
+          />
+          &nbsp;
+          <InputSelectRole
+            onChange={(ev) => handleRoleChange(ev, index)}
+            value={invite.role}
+            labelHidden={index !== 0}
+            short
```
Comment (iamsaumya) [inline app/scenes/Invite.js:201]: `Send Invites` button is not aligned with the `Select`. Either we will have to increase the modal size, or we can absolutely position the button below the select.

How would you go about this?

Comment (tommoor) [reply app/scenes/Invite.js:200]: Lets create an issue to implement the custom select with aim of fixing this
