### PR TITLE
fix: Choosing from suggestion menu with mouse inserts at incorrect position

### LINKED ISSUE #11309: Choosing from suggestion menu with mouse inserts at incorrect position
Create a notice block.
Inside, type `@`, choose from the menu with mouse instead of keyboard.

### PR DESCRIPTION
**Pull request by tommoor**
closes #11309

### CODE REVIEW

File: app/editor/components/SelectionToolbar.tsx [hunk 1]
```diff
@@ -155,13 +156,23 @@ export function SelectionToolbar(props: Props) {
         return;
       }
 
+      // Don't collapse selection if any suggestion menu is open
+      const isSuggestionMenuOpen = extensions.extensions.some(
+        (ext) => ext instanceof Suggestion && ext.isOpen
+      );
+      if (isSuggestionMenuOpen) {
```
Comment (tommoor) [inline app/editor/components/SelectionToolbar.tsx:163]: Meat of fix
