### PR TITLE
fix: New comments are measured incorrectly

### LINKED ISSUE #8834: Overlapping comments when adding new comment in sidebar
Image

### PR DESCRIPTION
**Pull request by tommoor**
closes #8834
regressed in https://github.com/outline/outline/pull/8338

### CODE REVIEW

File: shared/hooks/useComponentSize.ts [hunk 1]
```diff
@@ -21,23 +21,14 @@ export function useComponentSize(
...
-    const sizeObserver = new ResizeObserver(() => {
-      element?.dispatchEvent(new CustomEvent("resize"));
-    });
-    if (element) {
-      sizeObserver.observe(element);
-    }
-    return () => sizeObserver.disconnect();
-  }, [element]);
+  const [size, setSize] = useState<DOMRect | undefined>(
+    () => element?.getBoundingClientRect() || new DOMRect()
```
Comment (tommoor) [inline shared/hooks/useComponentSize.ts:25]: This is the actual fix, ensuring this is set avoids the size being skipped on L34

File: shared/hooks/useComponentSize.ts [hunk 2]
```diff
@@ -63,5 +55,15 @@ export function useComponentSize(
     };
   });
 
+  useLayoutEffect(() => {
```
Comment (tommoor) [inline shared/hooks/useComponentSize.ts:58]: Moved this afterwards as it makes sense to setup the listeners _after_ the handlers.

File: shared/hooks/useComponentSize.ts (hunk 1 above)
Comment (hmacr) [reply shared/hooks/useComponentSize.ts:25]: I might be wrong, this seems unnecessary with the call to `handleResize` on uLE setup 🤔 Let me test and see if this works well without it.

Comment (tommoor) [reply shared/hooks/useComponentSize.ts:14]: It's very finicky

File: shared/hooks/useComponentSize.ts [hunk 3]
```diff
@@ -55,6 +46,7 @@ export function useComponentSize(
     window.addEventListener("click", handleResize);
     window.addEventListener("resize", handleResize);
     element?.addEventListener("resize", handleResize);
+    handleResize();
 
     return () => {
```
Comment (hmacr) [inline shared/hooks/useComponentSize.ts:41]: Not a feedback on this PR.. totally unrelated TIL for me - in these cases of cleaning up multiple event listeners, using an AbortController's signal makes it very neat :)

https://kettanaito.com/blog/dont-sleep-on-abort-controller

Comment (tommoor) [reply shared/hooks/useComponentSize.ts:41]: TIL indeed!

File: shared/hooks/useComponentSize.ts (hunk 1 above)
Comment (hmacr) [reply shared/hooks/useComponentSize.ts:14]: Doesn't work without it - not worth debugging I suppose.

**Review by hmacr — APPROVED** [review]
Tested 👍
