### PR TITLE
fix: Meta key shortcuts not bound correctly in Windows browsers

### LINKED ISSUE #1745: (Other) Shortcuts not working for Windows
Ctrl-Enter/Ctrl-Shift-P doesn't work on Windows.

This bug may be related to https://github.com/outline/outline/issues/525.

**To Reproduce**
1. Be on a Windows machine (I'm on Windows 10)
2. Create a new doc
3. type something in, like "test"
4. attempt to save page using `Ctrl+Enter`, or publish via `Ctrl-Shift-P`
5. see that it does not publish, save, or save draft

**Expected behavior**

Publish, save, and save draft shortcuts should work in a document.

**Screenshots**

image

Instead of publishing, I get a print dialog for example when I press `Ctrl-Shift-P`

**Outline (please complete the following information):**
- Install: self-hosted
- Version: v0.51.0 - https://github.com/outline/outline/commit/574fcc4bb337243178a9160f01008f64e11d6e38

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 87

### PR DESCRIPTION
**Pull request by tommoor**
- Removes incorrect use of `event.metaKey` (It's the Windows key on Windows)
- Adds additional helpers and utils for keybinding
- Fixes shortcuts incorrectly bound to Windows key

closes #1745

### CODE REVIEW

File: app/scenes/KeyboardShortcuts.js [hunk 1]
```diff
@@ -41,9 +41,13 @@ function KeyboardShortcuts() {
...
         <Label>{t("Jump to dashboard")}</Label>
         <Keys>
-          <Key>{meta}</Key> + <Key>Ctrl</Key> + <Key>h</Key>
+          <Key>{metaDisplay}</Key> + <Key>Ctrl</Key> + <Key>h</Key>
         </Keys>
         <Label>{t("Table of contents")}</Label>
+        <Keys>
+          <Key>{metaDisplay}</Key> + <Key>.</Key>
+        </Keys>
+        <Label>{t("Toggle sidebar")}</Label>
```
Comment (tommoor) [inline app/scenes/KeyboardShortcuts.js:50]: Add missing (newly added) shortcut for toggling sidebar while we're here.
