### PR TITLE
fix: Unnecessary shares.info request when loading public share

### LINKED ISSUE #1450: Loading share link makes unnecessary request to shares.info
**To Reproduce**
1. Go to a share link
2. View network tab
3. See 401 request

### PR DESCRIPTION
**Pull request by tommoor**
closes #1450

### CODE REVIEW

File: app/scenes/Document/components/DataLoader.js [hunk 1]
```diff
@@ -125,17 +119,28 @@ class DataLoader extends React.Component<Props> {
...
       }
 
-      this.props.shares.fetch(document.id).catch((err) => {
-        if (!(err instanceof NotFoundError)) {
-          throw err;
-        }
-      });
+      // Prevents unauthorized request to load share information for the document
+      // when viewing a public share link
+      if (can.read) {
```
Comment (tommoor) [inline app/scenes/Document/components/DataLoader.js:137]: 🍖

File: app/scenes/Document/components/DataLoader.js [hunk 2]
```diff
@@ -125,17 +119,28 @@ class DataLoader extends React.Component<Props> {
...
+
+      // sets the document as active in the sidebar, ideally in the future this
+      // will be route driven.
       this.props.ui.setActiveDocument(document);
 
-      if (document.isArchived && this.isEditing) {
-        return this.goToDocumentCanonical();
+      // If we're attempting to update an archived, deleted, or otherwise
+      // uneditable document then forward to the canonical read url.
+      if (!can.update && this.isEditing) {
```
Comment (tommoor) [inline app/scenes/Document/components/DataLoader.js:130]: 📔  Cleanup to also use policies while we're here, this will catch the case of attempting to edit a hard deleted document too.
