### PR TITLE
Set subscribe/unsubscribe state correctly for documents

### LINKED ISSUE #4103: Subscribe/Unsubscribe state in document menu is incorrect before document has been viewed
The data for this is loaded when you view the doc, meaning if you go to a document menu before it's loaded it will always show "Subscribe" – even when you already are.

### PR DESCRIPTION
**Pull request by apoorv-mishra**
Closes #4103

### CODE REVIEW

File: app/menus/DocumentMenu.tsx [hunk 1]
```diff
@@ -95,8 +97,35 @@ function DocumentMenu({
   });
   const { t } = useTranslation();
   const isMobile = useMobile();
+  const [subscriptionsLoaded, onLoad, onError] = useBoolean(false);
```
Comment (apoorv-mishra) [inline app/menus/DocumentMenu.tsx:100]: Using local state purposely here since `subscriptions.isLoaded` is set _once and for all_ documents.

Comment (tommoor) [reply app/menus/DocumentMenu.tsx:100]: We have too many one-offs like this, it's time to create something reusable… how about a hook:

```typescript
import * as React from "react";
import { client } from "~/utils/ApiClient";

export default function useApiRequest<T>(
  path: string,
  params?: Record<string, any> | undefined
): {
  data: T | undefined;
  error: any;
  loading: boolean;
  request: () => Promise<void>;
} {
  const [data, setData] = React.useState();
  const [loading, setLoading] = React.useState(false);
  const [error, setError] = React.useState();

  const request = React.useCallback(async () => {
    setLoading(true);
    try {
      const response = await client.post(path, params);
      setData(response);
    } catch (err) {
      setError(err);
    } finally {
      setLoading(false);
    }
  }, [path, params]);

  return { data, loading, error, request };
}
```

Comment (tommoor) [reply app/menus/DocumentMenu.tsx:100]: Designed as a generic hook, for this case actually it would be better if it took a promise instead of a `path` and `params` so that we can use the existing store methods like:

```typescript
const { data, loading, request } = useRequest(() => subscriptions.fetchPage({
  documentId: document.id,
  event: "documents.update",
}));

if (!data && !loading) {
  request();
}
```

Comment (apoorv-mishra) [reply app/menus/DocumentMenu.tsx]: Yeah, tested and pushed. Seems to work fine.

**Review by tommoor — APPROVED** [review]
