### PR TITLE
Bring back notice menu

### LINKED ISSUE #10859: Unable to access toolbar for notices
> When we insert a "note", "tip" or "warning" we could change the type of the box on the upper right corner. We noticed today 11th of dec, that this isn't possible any more.

Another regression from that refactor

### PR DESCRIPTION
**Pull request by apoorv-mishra**
Closes #10859

### CODE REVIEW

File: app/editor/components/SelectionToolbar.tsx [hunk 1]
```diff
@@ -102,6 +102,8 @@ export function SelectionToolbar(props: Props) {
       setActiveToolbar(Toolbar.Menu);
     } else if (!selection.empty) {
       setActiveToolbar(Toolbar.Menu);
+    } else if (isNoticeSelection && selection.empty) {
```
Comment (tommoor) [inline app/editor/components/SelectionToolbar.tsx:106]: Where is `isNoticeSelection` coming from?

**Review by tommoor — APPROVED** [review]
