### PR TITLE
fix: SVGs without a natural px width are invisible

### LINKED ISSUE #3211: SVG images are not scaled correctly in Firefox
- Upload a large SVG image
- It uploads correctly but is incredibly small (invisible) in the doc
- Only in Firefox. Removing the max-height css clause gets it to appear.

### PR DESCRIPTION
**Pull request by tommoor**
closes #3211

### CODE REVIEW

File: shared/editor/nodes/Image.tsx [hunk 1]
```diff
@@ -520,6 +497,53 @@ export default class Image extends Node {
...
+  const [width, setWidth] = React.useState(0);
+
+  return (
+    <div contentEditable={false} className={className}>
+      <ImageWrapper
+        className={isSelected ? "ProseMirror-selectednode" : ""}
+        onClick={props.onClick}
+        style={{ width }}
+      >
+        <Button onClick={props.onDownload}>
```
Comment (tommoor) [inline shared/editor/nodes/Image.tsx:519]: Move `onClick` to the button, no idea why it was on the icon

File: shared/editor/nodes/Image.tsx [hunk 2]
```diff
@@ -576,10 +600,12 @@ const Caption = styled.p`
   }
 `;
 
-const ImageWrapper = styled.span`
+const ImageWrapper = styled.div`
   line-height: 0;
-  display: inline-block;
```
Comment (tommoor) [inline shared/editor/nodes/Image.tsx:581]: Not using `inline-block` also pretty important for Firefox compat
