### PR TITLE
fix: Move "public document sharing" to "Permissions"

### LINKED ISSUE #2483: Move "public document sharing" to "Permissions"
- Currently the setting for "Public document sharing" in a collection is inside the "Edit…" modal, it would be better placed in the "Permissions" modal below the default visibility and before individual member access.

image

### LINKED ISSUE #2487: Add `collections.permission_changed` event
Currently in the event log it's not possible to tell the difference between someone editing a collection title/description or completely changing the access permission, we need to separate these two actions into different events.

### PR DESCRIPTION
**Pull request by iamsaumya**
closes #2483 
closes #2487

### CODE REVIEW

File: server/events.js [hunk 1]
```diff
@@ -145,6 +145,18 @@ export type CollectionEvent =
...
       data: { index: string },
       ip: string,
+    }
+  | {
+      name: "collections.permission_changed",
+      collectionId: string,
+      teamId: string,
+      actorId: string,
+      data: {
+        index: string,
```
Comment (tommoor) [inline server/events.js:155]:
```suggestion
```

File: server/api/collections.js [hunk 2]
```diff
@@ -562,9 +563,17 @@ router.post("collections.update", auth(), async (ctx) => {
     collection.color = color;
   }
   if (permission !== undefined) {
+    // frontend sends empty string
+    ctx.assertIn(
+      permission,
+      ["read_write", "read", "", null],
```
Comment (tommoor) [inline server/api/collections.js:569]:
```suggestion
      ["read_write", "read", ""],
```

Can it really be `null`?

Comment (iamsaumya) [reply server/api/collections.js:569]: Some tests pass `null` I didn't update them with `""` thinking it must be some legacy feat that we are taking care of.

**Review by tommoor — APPROVED** [review]
