### PR TITLE
API to fetch users who have read/write permission on a document collection

### LINKED ISSUE #5032: @mentions shows users without access to the collection
**To Reproduce**
1. Make a collection "No access"
2. Go to a document within the collection
3. Type "@"
4. Users will appear that do not have access to the document / collection

**Expected behavior**
You should only be able to mention users with access

### PR DESCRIPTION
**Pull request by apoorv-mishra**
Closes #5032 

Currently, we don't have document level permissions for users so we base it on collection level permissions.

- [x] Add `documents.users` endpoint
- [x] Tests for `documents.users`
- [x] Replace `users.fetchPage` call in `MentionsMenu` with `documents.users` call

### CODE REVIEW

File: server/routes/api/documents/documents.ts [hunk 1]
```diff
@@ -435,6 +436,49 @@ router.post(
...
+    const { user } = ctx.state.auth;
+    const document = await Document.findByPk(id);
+    authorize(user, "update", document);
+
+    let users: User[] = [];
+
+    if (document.collectionId) {
+      const collection = await Collection.findByPk(document.collectionId);
+      authorize(user, "update", collection);
+      const memberIds = await Collection.membershipUserIds(collection.id);
```
Comment (apoorv-mishra) [inline server/routes/api/documents/documents.ts:454]: This doesn't include the `createdBy` user of the document. Should we include it separately?

Comment (tommoor) [reply server/routes/api/documents/documents.ts:454]: I don't think so as they don't necessarily retain access to the document if it's been moved between collections or their permissions have changed

**Comment by apoorv-mishra** [comment]
@tommoor you seem to have later modified `users.fetchPage` call [here](https://github.com/outline/outline/blob/21a44428f49d6d1d70655ed6d240964594e5d75c/app/editor/components/MentionMenu.tsx#L43). I assume it was to narrow down search space by filtering out inactive users, thereby making it efficient? If so, I don't think it's needed anymore for this new endpoint since we've already narrowed down users to `collection.membershipUserIds` here, which practically would be a much smaller number compared to _all users_.

**Comment by tommoor** [comment]
It wasn’t for efficiency, it was because suspended users were showing up in the mention options

**Comment by apoorv-mishra** [comment]
I see. A little eyeballing at `users.list` showed me `[Op.is]: null` for `suspendedAt` so I assumed it was the default filter anyway. Nonetheless, I believe we want to filter out suspended users for `documents.users` as well, right?

**Comment by tommoor** [comment]
> I believe we want to filter out suspended users for documents.users as well, right?

Yep yep!

File: server/routes/api/documents/documents.ts [hunk 2]
```diff
@@ -435,6 +436,52 @@ router.post(
   }
 );
 
+router.post(
+  "documents.users",
```
Comment (apoorv-mishra) [inline server/routes/api/documents/documents.ts:440]: Should we paginate this yet? :thinking:

Comment (tommoor) [reply server/routes/api/documents/documents.ts:440]: Yes, unfortunately we have 1000+ member collections to think of

File: shared/utils/parseDocumentSlug.ts
Comment (apoorv-mishra) [inline shared/utils/parseDocumentSlug.ts:1]: Returning `""` instead of `undefined` because it helps dealing with nasty type errors. I don't think `undefined` here is particularly used for any specific purpose, as far as `falsy` test is concerned, `""` equally works.

File: shared/utils/parseDocumentSlug.ts [hunk 3]
```diff
@@ -13,11 +13,11 @@ export default function parseDocumentSlug(url: string) {
     try {
       parsed = new URL(url).pathname;
     } catch (err) {
-      return;
+      return "";
```
Comment (apoorv-mishra) [inline shared/utils/parseDocumentSlug.ts:16]: Returning `""` instead of `undefined` because it helps in dealing with nasty type errors. I don't think `undefined` here is particularly used for any specific purpose and as far as _falsy_ tests are concerned, `""` equally works.

File: app/editor/components/MentionMenu.tsx [hunk 4]
```diff
@@ -36,12 +38,14 @@ type Props = Omit<
...
+  const { documents, auth } = useStores();
+  const location = useLocation();
+  const documentId = parseDocumentSlug(location.pathname);
   const { view } = useEditor();
   const { data, request } = useRequest(
     React.useCallback(
-      () => users.fetchPage({ query: search, filter: "active" }),
-      [users, search]
+      () => documents.fetchUsers({ id: documentId, query: search }),
+      [documents, search]
```
Comment (tommoor) [inline app/editor/components/MentionMenu.tsx:48]: `documentId` should be in dependencies too, no?

File: app/stores/DocumentsStore.ts [hunk 5]
```diff
@@ -281,6 +282,24 @@ export default class DocumentsStore extends BaseStore<Document> {
     });
   };
 
+  @action
+  fetchUsers = async (
```
Comment (tommoor) [inline app/stores/DocumentsStore.ts:286]: I don't think there is a _right_ answer of where to put this, but I would sway to towards the users store as the entity being requested and stored is a `User`.

File: shared/utils/parseDocumentSlug.ts (hunk 3 above)
Comment (tommoor) [reply shared/utils/parseDocumentSlug.ts:16]: I think it's useful in that it stops you in making a useless request to `document.users` with an empty id. Instead we can guard against that and make no request at all of this returns `undefined`?

File: server/routes/api/documents/documents.ts [hunk 6]
```diff
@@ -435,6 +436,59 @@ router.post(
...
+  auth(),
+  pagination(),
+  validate(T.DocumentsUsersSchema),
+  async (ctx: APIContext<T.DocumentsUsersReq>) => {
+    const { id, query } = ctx.input.body;
+    const actor = ctx.state.auth.user;
+    const { offset, limit } = ctx.state.pagination;
+    const document = await Document.findByPk(id);
+    authorize(actor, "update", document);
```
Comment (tommoor) [inline server/routes/api/documents/documents.ts:449]:
```suggestion
    authorize(actor, "read", document);
```

read is enough otherwise viewers won't be able to mention other users in comments

File: server/routes/api/documents/documents.ts (hunk 1 above)
Comment (tommoor) [reply server/routes/api/documents/documents.ts:457]: Totally forgot we had this method

File: app/editor/components/MentionMenu.tsx (hunk 4 above)
Comment (apoorv-mishra) [reply app/editor/components/MentionMenu.tsx:48]: Yes!

File: shared/utils/parseDocumentSlug.ts (hunk 3 above)
Comment (apoorv-mishra) [reply shared/utils/parseDocumentSlug.ts:16]: Better :+1:

File: server/routes/api/documents/documents.ts (hunk 6 above)
Comment (apoorv-mishra) [reply server/routes/api/documents/documents.ts:449]: Okay...How do I test this? Sorry, but it's not clear how to add comments. Ideally it should be an item of the toolbar that pops up upon text selection but I don't see it there. Or is it hidden behind some feature flag for now?

Comment (tommoor) [reply server/routes/api/documents/documents.ts]: Currently viewers cannot add comments on a text selection – they can add comments to the document though through the sidebar, and can reply to existing comments

File: server/routes/api/documents/documents.ts [hunk 7]
```diff
@@ -435,6 +436,59 @@ router.post(
...
+    const document = await Document.findByPk(id);
+    authorize(actor, "read", document);
+
+    let users: User[] = [];
+    let total = 0;
+
+    if (document.collectionId) {
+      const collection = await Collection.findByPk(document.collectionId);
+      authorize(actor, "update", collection);
+      const memberIds = await Collection.membershipUserIds(collection.id);
```
Comment (tommoor) [inline server/routes/api/documents/documents.ts:457]:
```suggestion
      const [collection, memberIds] = Promise.all([
        Collection.findByPk(document.collectionId),
        Collection.membershipUserIds(document.collectionId)
      ]);
      authorize(actor, "update", collection);
```

I think it would be worth running these in parallel

File: server/routes/api/documents/documents.ts [hunk 8]
```diff
@@ -435,6 +436,59 @@ router.post(
...
+        User.findAll({ where, offset, limit }),
+        User.count({ where }),
+      ]);
+    }
+
+    ctx.body = {
+      pagination: { ...ctx.state.pagination, total },
+      data: users.map((user) =>
+        presentUser(user, { includeDetails: can(actor, "readDetails", user) })
+      ),
```
Comment (tommoor) [inline server/routes/api/documents/documents.ts:486]:
```suggestion
      data: users.map((user) => presentUser(user)),
```

No need for any extra details here

**Review by tommoor — APPROVED** [review]

File: app/stores/UsersStore.ts [hunk 9]
```diff
@@ -159,6 +159,25 @@ export default class UsersStore extends BaseStore<User> {
     return res.data;
   };
 
+  @action
+  fetchDocumentUsers = async (params: {
```
Comment (tommoor) [inline app/stores/UsersStore.ts:163]: All these `fetchBlah` calls are super similar, it would be good to refactor and cleanup how this is done in stores if you care to in a separate PR.

Comment (apoorv-mishra) [reply app/stores/UsersStore.ts:163]: Similar in manner to `fetchDrafts`, `fetchArchived` etc. of `DocumentsStore`?
