### PR TITLE
fix: Cannot load avatars in some instances

### LINKED ISSUE #8935: Avatars fail to load with 404 error in v0.83.0
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This is not related to configuring Outline

- [x] The issue is not related to self-hosting config

### Current Behavior

Hey Outline team! 👋 I'm reporting an issue where user avatars aren't loading correctly after logging in via CASDOOR OIDC. Specifically, when trying to fetch an avatar, the API returns a 404 error, even though the file exists in the Docker volume. 

Image

### Expected Behavior

avatars should load correctly without any errors. The API should return the file resource if it exists in the volume, resulting in a successful image display (e.g., HTTP 200 status with the image data).

### Steps To Reproduce

1. Set up Outline v0.83.0 with CASDOOR OIDC authentication enabled.
2. Log in to Outline using a CASDOOR OIDC account.
3. Navigate to outline /settings/members where avatars are displayed.
4. Observe the avatar request failing with a 404 error on the API endpoint: `https://outline.mydomin.com/api/files.get?key=avatars/241ce70d-450b-4c4c-94ab-f16802fcc6cf/308dd2a6-a9b9-4f73-a14c-4f242205c944`.
`{"ok":false,"error":"not_found","status":404,"message":"Resource not found"}`
Image

5. Verify the file exists in the Docker volume.

Image

### Environment

```markdown
- Outline:0.83.0
- Browser:Edge,Chrome
```

### Environment

- **Outline Version:** v0.83.0
- **Operating System:** Windows11 WSL docker
- **Browser:** Chrome 135.0.7049.85, Edge 135.0.3179.66; 
- **Docker Version:** Docker version 27.1.1, build 6312585
- **OIDC Provider:** CASDOOR

**Key details:**
- API endpoint: `https://outline.mydomin.com/api/files.get?key=avatars/241ce70d-450b-4c4c-94ab-f16802fcc6cf/308dd2a6-a9b9-4f73-a14c-4f242205c944`
- Error response: `{"ok":false,"error":"not_found","status":404,"message":"Resource not found"}`
- I've confirmed the resource exists in the Docker volume, but it's not being accessed successfully.

**Possible cause:** This could be related to how OIDC authentication handles file paths or permissions. For e.g., the OIDC flow might not be passing the correct context or tokens needed for the API to resolve the file key, leading to a "not found" error despite the file being present. IMO, it might involve misconfigurations in Outline's OIDC integration, such as incorrect URL mappings, authentication scopes, or Docker volume mounting issues that affect file accessibility post-login.

### PR DESCRIPTION
**Pull request by tommoor**
closes #8935

### CODE REVIEW

**Comment by hmacr** [comment]
At some point, I think it'd be better to start using a single bucket for avatars - right now, avatars uploads from within Outline use the _public_ bucket while these OIDC flows use _avatars_ bucket.

File: plugins/storage/server/api/files.ts [hunk 1]
```diff
@@ -78,17 +78,13 @@ router.get(
     const { isPublicBucket, fileName } = AttachmentHelper.parseKey(key);
     const skipAuthorize = isPublicBucket || isSignedRequest;
     const cacheHeader = "max-age=604800, immutable";
-
-    const attachment = await Attachment.findOne({
-      where: { key },
-    });
-
-    // Attachment is requested with a key, but it was not found
-    if (!attachment && !!ctx.input.query.key) {
```
Comment (hmacr) [inline plugins/storage/server/api/files.ts:87]: What I don't get is, avatar requests must have failed with 404 in the previous versions as well, given db request would have thrown a not found error 🤔 

https://github.com/outline/outline/pull/8524/files#diff-26a1619ef7484a9d9fcd5eee18e291e33994bd335a9f7da57ede9ce674efb825L83

Comment (tommoor) [reply plugins/storage/server/api/files.ts:87]: It would have been this change where the Attachment call moved outside `skipAuthorize`

https://github.com/outline/outline/commit/f46921275dca713d25e953c2c7610dec5d030d28#diff-26a1619ef7484a9d9fcd5eee18e291e33994bd335a9f7da57ede9ce674efb825L85

I was under the impression that all files had an associated attachment, but it's not the case.

Comment (hmacr) [reply plugins/storage/server/api/files.ts:87]: oooh, that makes sense.

**Comment by tommoor** [comment]
I want to add a couple more tests here for files missing from filesystem before merging
