### PR TITLE
fix: Add Polish to language choices

### LINKED ISSUE #2564: Add Polish to language choices
First translation in CrownIn is now complete.

### PR DESCRIPTION
**Pull request by iamsaumya**
closes #2564

### CODE REVIEW

**Comment by iamsaumya** [comment]
Ahh! These tests now fail consistently :/

**Comment by tommoor** [comment]
I think you just need to pull master in, it was fixed last week

File: shared/i18n/index.js [hunk 1]
```diff
@@ -4,7 +4,7 @@ import backend from "i18next-http-backend";
 import { initReactI18next } from "react-i18next";
 
 // Note: Updating the available languages? Make sure to also update the
-// locales array in app/components/LocaleTime.js to enable translation for timestamps.
+// locales array in app/utils/i18n.js to enable translation for timestamps.
```
Comment (tommoor) [inline shared/i18n/index.js:7]: 🙏
