### PR TITLE
Throttle email notifications upon updating document frequently

### LINKED ISSUE #3467: Reduce email notifications when a document is modified multiple times
Someone has modified a page I modified previously, so I received a mail notification.
Another person modified the same page again few minutes later and I've got a second notification.

The second notification is useless (imho) because I did not visit or modified the page since I've received the first notification.

**To Reproduce**
1. Someone modify a page I previously modified
2. I receive a notification mail
3. Another person edits the same page
4. step 2. happen again

**Expected behavior**
Just being notified once.

**Screenshots**
null

**Outline (please complete the following information):**
- Install: self-hosted
- Version: 0.63.0

**Desktop (please complete the following information):**
 - OS: N/a
 - Browser [e.g. chrome, safari]: N/a
 - Version [e.g. 22]: N/a

**Mobile (please complete the following information):**
 - Device: [e.g. iPhone6] N/a
 - OS: [e.g. iOS8.1] N/a
 - Browser [e.g. stock browser, safari] N/a

### PR DESCRIPTION
**Pull request by apoorv-mishra**
Closes #3467

### CODE REVIEW

File: server/emails/templates/BaseEmail.tsx [hunk 1]
```diff
@@ -80,6 +81,21 @@ export default abstract class BaseEmail<T extends EmailProps, S = any> {
       Metrics.increment("email.sent", {
         templateName,
       });
+
+      // @ts-expect-error does not exist on type T & S
```
Comment (tommoor) [inline server/emails/templates/BaseEmail.tsx:85]: This is unfortunate, the types have been tricky here with it being static. Perhaps we can define S as an object which always has an optional `notificationId`?

File: server/emails/templates/BaseEmail.tsx [hunk 2]
```diff
@@ -80,6 +81,21 @@ export default abstract class BaseEmail<T extends EmailProps, S = any> {
...
+      if (data.notificationId) {
+        await Notification.update(
```
Comment (tommoor) [inline server/emails/templates/BaseEmail.tsx:87]: I'm worried that this within the try/catch could cause an email to be sent twice if it fails, better to move outside the try and fail with a Logger

File: server/queues/processors/NotificationsProcessor.ts [hunk 3]
```diff
@@ -237,6 +247,23 @@ export default class NotificationsProcessor extends BaseProcessor {
       return false;
     }
 
+    // Deliver only a single notification in a 12 hour window
+    const notification = await Notification.findOne({
+      order: [["createdAt", "DESC"]],
+      where: {
+        userId: user.id,
+        documentId: document.id,
+        emailedAt: {
```
Comment (tommoor) [inline server/queues/processors/NotificationsProcessor.ts:256]: Need to make sure this has an index in the migration (see previous migrations for examples)

File: server/emails/templates/BaseEmail.tsx (hunk 2 above)
Comment (apoorv-mishra) [reply server/emails/templates/BaseEmail.tsx:87]: Thanks for spotting this :pray:

File: server/emails/templates/BaseEmail.tsx (hunk 1 above)
Comment (apoorv-mishra) [reply server/emails/templates/BaseEmail.tsx]: Added on both `T` and `S`.

Comment (apoorv-mishra) [reply server/emails/templates/BaseEmail.tsx]: What is we add it `T` instead? `S = Optional<...>` thingy doesn't work since `S` would still be _unknown_. On the other hand, `S extends...` makes it _required_ which in result demands modifications at other places too.

Comment (apoorv-mishra) [reply server/emails/templates/BaseEmail.tsx]: Or how about having and optional `metadata` field(`metadata?: Required<{ notificationId: string }>;`) in top level `EmailProps` instead? I guess that's better.

File: server/emails/templates/BaseEmail.tsx [hunk 4]
```diff
@@ -86,6 +88,28 @@ export default abstract class BaseEmail<T extends EmailProps, S = any> {
...
+            where: {
+              id: metadata.notificationId,
+            },
+          }
+        );
+      } catch (err) {
+        Logger.error(
+          `Failed to update notification(id=${metadata.notificationId})`,
+          err
+        );
```
Comment (tommoor) [inline server/emails/templates/BaseEmail.tsx:110]:
```suggestion
        Logger.error(
          `Failed to update notification`,
          err,
          metadata,
        );
```

You can pass structured data to be stored with the error log as third argument 👍

File: server/queues/processors/NotificationsProcessor.ts [hunk 5]
```diff
@@ -72,6 +74,13 @@ export default class NotificationsProcessor extends BaseProcessor {
...
 
       if (notify) {
+        const notification = await Notification.create({
+          event: event.name,
+          userId: recipient.user.id,
+          actorId: document.updatedBy.id,
+          teamId: team.id,
+          documentId: document.id,
+        });
         await DocumentNotificationEmail.schedule({
```
Comment (tommoor) [inline server/queues/processors/NotificationsProcessor.ts:84]: What do you think about passing `metadata` as second argument instead of mixing in with email props?

File: server/queues/processors/NotificationsProcessor.ts [hunk 6]
```diff
@@ -237,6 +249,23 @@ export default class NotificationsProcessor extends BaseProcessor {
       return false;
     }
 
+    // Deliver only a single notification in a 12 hour window
+    const notification = await Notification.findOne({
```
Comment (tommoor) [inline server/queues/processors/NotificationsProcessor.ts:253]: I'm tempted to suggest we abstract the entire logic into a configuration on the email class so you can define the suppression rules per-email. But it's probably over engineering in this moment as I'm not sure if any other types of email will need similar logic to this, document edits is kind of a special case.

File: server/queues/processors/NotificationsProcessor.ts (hunk 5 above)
Comment (apoorv-mishra) [reply server/queues/processors/NotificationsProcessor.ts:84]: Hmm...makes sense from the POV of _decoupling_ it from email notifications. It might be needed for other types of notifications(in-app etc...) as well. What's your reasoning?

File: server/queues/processors/NotificationsProcessor.ts (hunk 6 above)
Comment (apoorv-mishra) [reply server/queues/processors/NotificationsProcessor.ts:253]: Actually, it occurred to me as well. My suggestion is that we place the suppression rules as it is for now since we don't have many yet. The `shouldNotify` is good enough, since it's explicit and more importantly _keeps all suppression rules in one place_. Not in favor of detouring yet. Makes more sense once we have a clear distinction of suppression rules based on notification types.

File: server/queues/processors/NotificationsProcessor.ts (hunk 5 above)
Comment (tommoor) [reply server/queues/processors/NotificationsProcessor.ts:84]: Reasoning is mainly they are functionally different data use, the first being for template injection.

**Review by tommoor — APPROVED** [review]
