### PR TITLE
fix: Incorrect plain text serialization in `exportTable`

### LINKED ISSUE #8230: CSV Export with linked Members not exporting
**To Reproduce**
1. Create a table
2. Add members of the workspace with @member_name_1, @member_name_2
3. Export the table as CSV (upper left corner of the table)
4. in the CSV the members show as blank space

**Expected behavior**
Member names should be visible in CSV

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.81.1

### PR DESCRIPTION
**Pull request by tommoor**
closes #8230

### CODE REVIEW

File: shared/editor/lib/textSerializers.ts [hunk 1]
```diff
@@ -0,0 +1,14 @@
+import { Schema } from "prosemirror-model";
+
+/**
+ * Generate a map of text serializers for a given schema
+ * @param schema
+ * @returns Text serializers
+ */
+export function getTextSerializers(schema: Schema) {
```
Comment (tommoor) [inline shared/editor/lib/textSerializers.ts:8]: DRYing this up while we're here
