### PR TITLE
fix: One source of transaction deadlock when invites > pg pool

### LINKED ISSUE #1695: Intermitent transaction deadlock
**To Reproduce**

In production we've seen an occasional transaction deadlock, logged as `SequelizeConnectionAcquireTimeoutError`. This causes the node process to lock up and timeout for other queries. The process often needs to be restarted to fully recover.

**Expected behavior**

No deadlocks would be nice.

**Outline (please complete the following information):**
- Install: 0.50.0

### PR DESCRIPTION
**Pull request by tommoor**
closes #1695

### CODE REVIEW

File: server/commands/userInviter.js [hunk 1]
```diff
@@ -47,48 +47,33 @@ export default async function userInviter({
   let users = [];
 
   // send and record remaining invites
-  await Promise.all(
-    filteredInvites.map(async (invite) => {
-      const transaction = await sequelize.transaction();
```
Comment (tommoor) [inline server/commands/userInviter.js:52]: In hindsight the transaction was unnecessary here

File: server/commands/userSuspender.js [hunk 2]
```diff
@@ -16,29 +17,27 @@ export default async function userSuspender({
     throw new ValidationError("Unable to suspend the current user");
   }
 
-  let transaction;
-  try {
-    transaction = await sequelize.transaction();
```
Comment (tommoor) [inline server/commands/userSuspender.js:21]: Transaction was created but not committed or used here, big oversight
