### PR TITLE
fix: Store Linear workspace logo in storage

### LINKED ISSUE #9054: Linear workspace logo needs to be moved to Outline storage
On connect we need to upload the image to our own storage as it's an authenticated presigned URL that does not last long.

Similar to when connecting a workspace, `FileStorage.storeFromUrl` can be used.

### PR DESCRIPTION
**Pull request by hmacr**
Closes #9054

### CODE REVIEW

File: plugins/linear/server/api/linear.ts [hunk 1]
```diff
@@ -72,6 +75,18 @@ router.get(
     const oauth = await Linear.oauthAccess(code!);
     const workspace = await Linear.getInstalledWorkspace(oauth.access_token);
 
+    let logoUrl: string | undefined;
+
+    if (workspace.logoUrl) {
+      const res = await FileStorage.storeFromUrl(
```
Comment (hmacr) [inline plugins/linear/server/api/linear.ts:81]: Contemplating doing this here vs in a background task.
This is simpler, however background task reduces the redirect latency a lot.

**Comment by hmacr** [comment]
Has any customer started using Linear already? We might need patching the existing integrations in that case.

**Comment by tommoor** [comment]
I'll email them and have them reconnect if any have been recreated, won't be many

File: plugins/linear/server/api/linear.ts [hunk 2]
```diff
@@ -103,6 +106,13 @@ router.get(
       { transaction }
     );
 
+    transaction.afterCommit(async () => {
```
Comment (tommoor) [inline plugins/linear/server/api/linear.ts:109]: We should probably generalize this soon, perhaps some `.scheduleWithCtx` or equivalent

File: plugins/linear/server/index.ts [hunk 3]
```diff
@@ -15,6 +16,10 @@ if (enabled) {
       type: Hook.API,
       value: router,
     },
+    {
```
Comment (tommoor) [inline plugins/linear/server/index.ts:19]: I moved the task into the plugin, lmk if you saw something I didnt

Comment (hmacr) [reply plugins/linear/server/index.ts:19]: Nah, this is right - I totally missed it :)
