### PR TITLE
fix: Flash of content when selecting text on RHS of document

### LINKED ISSUE #2977: Occasional flash of text content when selecting
Sometimes when you're selecting within the editor the text disappears for an individual frame, need to get to the bottom of this jank – it makes the editor feel much less "solid".

### PR DESCRIPTION
**Pull request by tommoor**
closes #2977

### CODE REVIEW

File: app/editor/components/FloatingToolbar.tsx [hunk 1]
```diff
@@ -146,54 +152,54 @@ function usePosition({
...
+        <Wrapper
+          active={props.active && position.visible}
+          ref={menuRef}
+          offset={position.offset}
+          style={{
+            top: `${position.top}px`,
+            left: `${position.left}px`,
+          }}
+        >
+          {props.children}
```
Comment (tommoor) [inline app/editor/components/FloatingToolbar.tsx:197]: Key is to always render the children otherwise the first render has the wrong width and it results in the toolbar being mispositioned off the right of the screen

File: app/editor/components/SelectionToolbar.tsx [hunk 2]
```diff
@@ -229,27 +229,25 @@ export default class SelectionToolbar extends React.Component<Props> {
     }
 
     return (
-      <Portal>
```
Comment (tommoor) [inline app/editor/components/SelectionToolbar.tsx:232]: Double portal – `FloatingToolbar` is already portalled

File: app/editor/components/ToolbarMenu.tsx [hunk 3]
```diff
@@ -14,12 +14,12 @@ type Props = {
 };
 
 const FlexibleWrapper = styled.div`
+  color: ${(props) => props.theme.toolbarItem};
   display: flex;
   gap: 8px;
 `;
 
 function ToolbarMenu(props: Props) {
-  const theme = useTheme();
```
Comment (tommoor) [inline app/editor/components/ToolbarMenu.tsx:22]: Just nice to avoid `useTheme` if not really needed

File: app/hooks/useComponentSize.ts [hunk 4]
```diff
@@ -4,8 +4,8 @@ export default function useComponentSize(
   ref: React.RefObject<HTMLElement>
 ): { width: number; height: number } {
   const [size, setSize] = useState({
-    width: 0,
-    height: 0,
+    width: ref.current?.clientWidth || 0,
```
Comment (tommoor) [inline app/hooks/useComponentSize.ts:7]: Should at least attempt to set the right size on mount
