### PR TITLE
fix: Handle GitLab can be configured for tokens to not expire.

### LINKED ISSUE #4040: throws ValidationError when log in and can't log in with E-mail
I updated Outline from v0.64.3 to v0.65.2 today.
When I logged out then logged in, Outline throwed a `ValidationError`.

Sometimes it works fine after reloading the web page, but keeps throwing `UnauthorizedError` in logs.
Sometimes it just simply crashes without further logs.

And when I log out and try with E-mail , it redirect me to GitLab authorization if the account exists, rather than sending me a magic link.

**To Reproduce**
1.  log out then log in

**Outline:**
- Install: self hosted on docker
- Version: v0.65.2
- Authoricate with self hosted GitLab

Here are the logs.
```
yarn run v1.22.18
$ sequelize db:migrate --env production-ssl-disabled

Sequelize CLI [Node: 16.14.2, CLI: 6.4.1, ORM: 6.20.1]

Loaded configuration file "server/config/database.json".
Using environment "production-ssl-disabled".
No migrations were executed, database schema was already up to date.
Done in 0.43s.
yarn run v1.22.18
$ node ./build/server/index.js
{"label":"lifecycle","level":"info","message":"Note: Restricting process count to 1 due to use of collaborative service"}
{"label":"lifecycle","level":"info","message":"\nIs your team enjoying Outline? Consider supporting future development by sponsoring the project:\n\nhttps://github.com/sponsors/outline\n"}
{"label":"lifecycle","level":"info","message":"Note: Restricting process count to 1 due to use of collaborative service"}
{"label":"lifecycle","level":"info","message":"Starting collaboration service"}
{"label":"lifecycle","level":"info","message":"Starting websockets service"}
{"label":"lifecycle","level":"info","message":"Starting worker service"}
{"label":"lifecycle","level":"info","message":"Starting web service"}
{"level":"warn","message":"Enforced https was disabled with FORCE_HTTPS env variable"}
{"label":"lifecycle","level":"info","message":"Listening on http://localhost:3000"}
{"name":"users.signin","modelId":null,"attempt":0,"label":"worker","level":"info","message":"Processing users.signin"}
{"name":"users.signin","modelId":null,"label":"worker","level":"info","message":"WebhookProcessor running users.signin"}
{"userId":"d9efae76-051e-46a0-af97-ec13f893e0fe","label":"worker","level":"info","message":"ValidateSSOAccessTask running"}
{"id":"be0283ca-a315-43b8-bc82-306f40d5b143","userId":"d9efae76-051e-46a0-af97-ec13f893e0fe","label":"utils","level":"info","message":"Refreshing expiring access token"}
{"id":"be0283ca-a315-43b8-bc82-306f40d5b143","userId":"d9efae76-051e-46a0-af97-ec13f893e0fe","label":"utils","level":"info","message":"Successfully refreshed expired access token"}
/opt/outline/node_modules/sequelize/lib/data-types.js:312
      throw new sequelizeErrors.ValidationError(util.format("%j is not a valid date", value));
            ^

ValidationError [SequelizeValidationError]: null is not a valid date
    at DATE.validate (/opt/outline/node_modules/sequelize/lib/data-types.js:312:13)
    at DATE.validate (/opt/outline/node_modules/sequelize/lib/dialects/postgres/data-types.js:126:22)
    at PostgresQueryGenerator.validate (/opt/outline/node_modules/sequelize/lib/dialects/abstract/query-generator.js:740:22)
    at PostgresQueryGenerator.format (/opt/outline/node_modules/sequelize/lib/dialects/abstract/query-generator.js:724:14)
    at PostgresQueryGenerator.updateQuery (/opt/outline/node_modules/sequelize/lib/dialects/abstract/query-generator.js:313:58)
    at PostgresQueryInterface.update (/opt/outline/node_modules/sequelize/lib/dialects/abstract/query-interface.js:352:37)
    at Object.save (/opt/outline/node_modules/sequelize/lib/model.js:2432:79)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errors: [
    ValidationErrorItem {
      message: 'null is not a valid date',
      type: 'Validation error',
      path: 'expiresAt',
      value: Invalid Date,
      origin: 'FUNCTION',
      instance: null,
      validatorKey: 'DATE validator',
      validatorName: null,
      validatorArgs: []
    }
  ]
}
{"label":"lifecycle","level":"info","message":"Note: Restricting process count to 1 due to use of collaborative service"}
{"label":"lifecycle","level":"info","message":"Starting collaboration service"}
{"label":"lifecycle","level":"info","message":"Starting websockets service"}
{"label":"lifecycle","level":"info","message":"Starting worker service"}
{"label":"lifecycle","level":"info","message":"Starting web service"}
{"level":"warn","message":"Enforced https was disabled with FORCE_HTTPS env variable"}
{"label":"lifecycle","level":"info","message":"Listening on http://localhost:3000"}
{"userId":"d9efae76-051e-46a0-af97-ec13f893e0fe","label":"worker","level":"info","message":"ValidateSSOAccessTask running"}
{"id":"be0283ca-a315-43b8-bc82-306f40d5b143","userId":"d9efae76-051e-46a0-af97-ec13f893e0fe","label":"utils","level":"info","message":"Refreshing expiring access token"}
{"error":"Invalid authentication","stack":"UnauthorizedError: Invalid authentication\n    at AuthenticationError (/opt/outline/build/server/errors.js:35:34)\n    at OIDCClient.rotateToken (/opt/outline/build/server/utils/oauth.js:75:47)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Object.refreshAccessTokenIfNeeded (/opt/outline/build/server/models/UserAuthentication.js:155:24)\n    at async Object.validateAccess (/opt/outline/build/server/models/UserAuthentication.js:110:7)\n    at async Promise.all (index 0)\n    at async /opt/outline/build/server/queues/tasks/ValidateSSOAccessTask.js:40:21\n    at async /opt/outline/node_modules/sequelize/lib/sequelize.js:503:18\n    at async ValidateSSOAccessTask.perform (/opt/outline/build/server/queues/tasks/ValidateSSOAccessTask.js:26:5)\n    at async Queue.<anonymous> (/opt/outline/build/server/services/worker.js:132:7)","level":"error","message":"Error processing task in ValidateSSOAccessTask"}
{"userId":"d9efae76-051e-46a0-af97-ec13f893e0fe","label":"worker","level":"info","message":"ValidateSSOAccessTask running"}
{"id":"be0283ca-a315-43b8-bc82-306f40d5b143","userId":"d9efae76-051e-46a0-af97-ec13f893e0fe","label":"utils","level":"info","message":"Refreshing expiring access token"}
{"error":"Invalid authentication","stack":"UnauthorizedError: Invalid authentication\n    at AuthenticationError (/opt/outline/build/server/errors.js:35:34)\n    at OIDCClient.rotateToken (/opt/outline/build/server/utils/oauth.js:75:47)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Object.refreshAccessTokenIfNeeded (/opt/outline/build/server/models/UserAuthentication.js:155:24)\n    at async Object.validateAccess (/opt/outline/build/server/models/UserAuthentication.js:110:7)\n    at async Promise.all (index 0)\n    at async /opt/outline/build/server/queues/tasks/ValidateSSOAccessTask.js:40:21\n    at async /opt/outline/node_modules/sequelize/lib/sequelize.js:503:18\n    at async ValidateSSOAccessTask.perform (/opt/outline/build/server/queues/tasks/ValidateSSOAccessTask.js:26:5)\n    at async Queue.<anonymous> (/opt/outline/build/server/services/worker.js:132:7)","level":"error","message":"Error processing task in ValidateSSOAccessTask"}
{"userId":"d9efae76-051e-46a0-af97-ec13f893e0fe","label":"worker","level":"info","message":"ValidateSSOAccessTask running"}
{"id":"be0283ca-a315-43b8-bc82-306f40d5b143","userId":"d9efae76-051e-46a0-af97-ec13f893e0fe","label":"utils","level":"info","message":"Refreshing expiring access token"}
{"error":"Invalid authentication","stack":"UnauthorizedError: Invalid authentication\n    at AuthenticationError (/opt/outline/build/server/errors.js:35:34)\n    at OIDCClient.rotateToken (/opt/outline/build/server/utils/oauth.js:75:47)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Object.refreshAccessTokenIfNeeded (/opt/outline/build/server/models/UserAuthentication.js:155:24)\n    at async Object.validateAccess (/opt/outline/build/server/models/UserAuthentication.js:110:7)\n    at async Promise.all (index 0)\n    at async /opt/outline/build/server/queues/tasks/ValidateSSOAccessTask.js:40:21\n    at async /opt/outline/node_modules/sequelize/lib/sequelize.js:503:18\n    at async ValidateSSOAccessTask.perform (/opt/outline/build/server/queues/tasks/ValidateSSOAccessTask.js:26:5)\n    at async Queue.<anonymous> (/opt/outline/build/server/services/worker.js:132:7)","level":"error","message":"Error processing task in ValidateSSOAccessTask"}
{"userId":"d9efae76-051e-46a0-af97-ec13f893e0fe","label":"worker","level":"info","message":"ValidateSSOAccessTask running"}
{"id":"be0283ca-a315-43b8-bc82-306f40d5b143","userId":"d9efae76-051e-46a0-af97-ec13f893e0fe","label":"utils","level":"info","message":"Refreshing expiring access token"}
{"error":"Invalid authentication","stack":"UnauthorizedError: Invalid authentication\n    at AuthenticationError (/opt/outline/build/server/errors.js:35:34)\n    at OIDCClient.rotateToken (/opt/outline/build/server/utils/oauth.js:75:47)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Object.refreshAccessTokenIfNeeded (/opt/outline/build/server/models/UserAuthentication.js:155:24)\n    at async Object.validateAccess (/opt/outline/build/server/models/UserAuthentication.js:110:7)\n    at async Promise.all (index 0)\n    at async /opt/outline/build/server/queues/tasks/ValidateSSOAccessTask.js:40:21\n    at async /opt/outline/node_modules/sequelize/lib/sequelize.js:503:18\n    at async ValidateSSOAccessTask.perform (/opt/outline/build/server/queues/tasks/ValidateSSOAccessTask.js:26:5)\n    at async Queue.<anonymous> (/opt/outline/build/server/services/worker.js:132:7)","level":"error","message":"Error processing task in ValidateSSOAccessTask"}
{"label":"hocuspocus","level":"info","message":"New connection to \"document.f5b4c5f5-90a5-40da-b6eb-0d90cd0007d0\""}
{"label":"database","level":"info","message":"Document f5b4c5f5-90a5-40da-b6eb-0d90cd0007d0 is in database state"}
{"userId":"d9efae76-051e-46a0-af97-ec13f893e0fe","label":"hocuspocus","level":"info","message":"Loaded document \"document.f5b4c5f5-90a5-40da-b6eb-0d90cd0007d0\""}
{"name":"views.create","modelId":"5c434faa-e6d6-4ad6-8cc3-588ae6c01a37","attempt":0,"label":"worker","level":"info","message":"Processing views.create"}
{"name":"views.create","modelId":"5c434faa-e6d6-4ad6-8cc3-588ae6c01a37","label":"worker","level":"info","message":"WebhookProcessor running views.create"}
```

### PR DESCRIPTION
**Pull request by tommoor**
closes #4040

### CODE REVIEW

File: server/models/UserAuthentication.ts [hunk 1]
```diff
@@ -162,7 +168,7 @@ class UserAuthentication extends IdModel {
       }
       this.accessToken = response.accessToken;
       this.expiresAt = response.expiresAt;
-      this.save(options);
+      await this.save(options);
```
Comment (tommoor) [inline server/models/UserAuthentication.ts:171]: Whoops, this meant the success log was shown even when it failed 🤦
