### PR TITLE
fix: auto-scroll sidebar to show active document

### LINKED ISSUE #7939: Sidebar does not always scroll automatically to show focused document
For me, the sidebar does not scroll automatically at all

_Originally posted by @matthew-ant in https://github.com/outline/outline/discussions/7931#discussioncomment-11227334_

### PR DESCRIPTION
**Pull request by hmacr**
Closes #7939 

Currently, starred documents and collections are not focused when they are opened.
As part of this PR, stars will now be prioritised for focus over the actual document / collection.

### CODE REVIEW

File: app/components/Sidebar/components/SidebarContext.ts [hunk 1]
```diff
@@ -1,9 +1,20 @@
 import * as React from "react";
 
-export type SidebarContextType = "collections" | "starred" | string | undefined;
+export type SidebarContextType =
```
Comment (hmacr) [inline app/components/Sidebar/components/SidebarContext.ts:3]: Refactored for type-safety

File: app/models/Document.ts [hunk 2]
```diff
@@ -429,6 +429,20 @@ export default class Document extends ArchivableModel {
     return this.title || i18n.t("Untitled");
   }
 
+  @computed
+  get membershipType(): "collection" | "direct" | "group" {
```
Comment (hmacr) [inline app/models/Document.ts:433]: Rename `direct` to `document`? Or something different maybe..?

File: app/components/Sidebar/components/SidebarContext.ts [hunk 3]
```diff
@@ -1,9 +1,20 @@
...
+  | "collections"
+  | "shared"
+  | `group-${string}`
```
Comment (tommoor) [inline app/components/Sidebar/components/SidebarContext.ts:6]: `group-${string}`

I had no idea you can do this… are you sure?

File: app/models/Document.ts (hunk 2 above)
Comment (tommoor) [reply app/models/Document.ts:433]: `document` is good

File: app/components/Sidebar/components/SidebarContext.ts (hunk 3 above)
Comment (hmacr) [reply app/components/Sidebar/components/SidebarContext.ts:6]: Yes, it works!

Comment (tommoor) [reply app/components/Sidebar/components/SidebarContext.ts:6]: mind blown

File: app/components/DocumentListItem.tsx [hunk 4]
```diff
@@ -78,6 +83,23 @@ function DocumentListItem(
     !!document.title.toLowerCase().includes(highlight.toLowerCase());
   const canStar = !document.isArchived && !document.isTemplate;
 
+  const membershipType = document.membershipType;
```
Comment (tommoor) [inline app/components/DocumentListItem.tsx:86]: This logic leads to some off behavior, for example if you are viewing a collection which contains a starred document and then click on that document it now jumps the sidebar to the top to focus it in the starred section.

We can probably lose this and `membershipType` but retain the rest of the fix?

Comment (hmacr) [reply app/components/DocumentListItem.tsx:86]: I'm afraid we need the `membershipType` so that shared docs to an user and within a group can be focused correctly in the sidebar.

re: stars: it was intentional to prefer stars over the actual document - It looks nice from "Home" page but it's unpleasant from "Collection" page 😞 I can think of a couple solutions.
1. Lose the whole "stars" priority? This will mean the stars won't be focused when opened from the document list in home / collections.
2. Focus the stars only if it's opened from Home?

Comment (tommoor) [reply app/components/DocumentListItem.tsx:86]: The second option seems ideal from a UX point of view, you're right... how to prevent this becoming overly complex

Comment (hmacr) [reply app/components/DocumentListItem.tsx:86]: We can listen to `history` events and conditionally update the location state based on the context in which the navigation happens. I think this helps centralize the logic, although it could become a bit complex to account for various navigations, e.g shared -> starred, home -> starred, shared -> shared, etc.

Comment (tommoor) [reply app/components/DocumentListItem.tsx:86]: I think `DocumentListItem` can be aware of where it's being rendered, either through a prop or a provider/context – we only need to know home for now so lets not over complicate.

Comment (hmacr) [reply app/components/DocumentListItem.tsx:86]: That was my initial thought, but there are quite a few cases which we can cover to provide a better UX. e.g. Navigate within the starred context when there's a link from a starred document to another starred document - This happens inside editor event handler, let me see if it's possible to cover them with the current solution 🤔 .

Comment (hmacr) [reply app/components/DocumentListItem.tsx]: Just updated the PR by introducing a function `determineSidebarContext` that uses the document and the current sidebar context to determine the next one.
Please note that most of the changes in this PR is forwarding the location state in case of any in-doc history updates.

File: app/scenes/Document/index.tsx [hunk 5]
```diff
@@ -32,6 +35,16 @@ export default function DocumentScene(props: Props) {
 
   React.useEffect(() => () => ui.clearActiveDocument(), [ui]);
 
+  React.useEffect(() => {
+    // When opening a document directly on app load, sidebarContext will not be set.
```
Comment (tommoor) [inline app/scenes/Document/index.tsx:39]: Oof, this is going to result in another render on every fresh document load :/

Comment (hmacr) [reply app/scenes/Document/index.tsx:39]: When we navigate between documents (both fresh and cached), this won't re-render since the location state will have sidebar context..
I think we'll have an additional render only when we navigate from a non-collection and non-document space 🤔

File: app/actions/definitions/comments.tsx [hunk 6]
```diff
@@ -55,7 +55,10 @@ export const resolveCommentFactory = ({
 
       history.replace({
         ...history.location,
-        state: null,
+        state: {
+          ...(history.location.state as Record<string, unknown>),
```
Comment (tommoor) [inline app/actions/definitions/comments.tsx:59]: I'm a bit worried about spreading the entire state like this, perhaps we should be picking just the `sidebarContext`? I don't want to have other random state following between navigations 🤔

File: app/components/Sidebar/components/StarredLink.tsx [hunk 7]
```diff
@@ -40,25 +40,35 @@ function StarredLink({ star }: Props) {
...
-      star.documentId === ui.activeDocumentId &&
-      sidebarContext === locationSidebarContext
-    ) {
-      setExpanded(true);
-    } else if (
-      star.collectionId === ui.activeCollectionId &&
-      sidebarContext === locationSidebarContext
-    ) {
-      setExpanded(true);
+    if (starType === "document") {
```
Comment (tommoor) [inline app/components/Sidebar/components/StarredLink.tsx:55]: I don't really know that this addition is neccessary?

File: app/components/Sidebar/components/StarredLink.tsx [hunk 8]
```diff
@@ -40,25 +40,35 @@ function StarredLink({ star }: Props) {
   const { documentId, collectionId } = star;
   const collection = collections.get(collectionId);
   const locationSidebarContext = useLocationState();
-  const sidebarContext = useSidebarContext();
+  const starType = star.documentId ? "document" : "collection";
+  const sidebarContext = starredSidebarContext(
+    starType === "document" ? star.documentId! : star.collectionId
```
Comment (tommoor) [inline app/components/Sidebar/components/StarredLink.tsx:45]:
```suggestion
    star.documentId ?? star.collectionId
```

?

File: app/scenes/Document/components/CommentThread.tsx [hunk 9]
```diff
@@ -101,7 +101,10 @@ function CommentThread({
       history.replace({
         search: location.search,
         pathname: location.pathname,
-        state: { commentId: undefined },
+        state: {
+          ...(location.state as Record<string, unknown>),
```
Comment (tommoor) [inline app/scenes/Document/components/CommentThread.tsx:105]: Similar re spreading everything

File: app/components/Sidebar/components/StarredLink.tsx (hunk 8 above)
Comment (hmacr) [reply app/components/Sidebar/components/StarredLink.tsx:45]: Yes, that works. Added the `starType` for readability - will remove it.

File: app/components/Sidebar/components/StarredLink.tsx (hunk 7 above)
Comment (hmacr) [reply app/components/Sidebar/components/StarredLink.tsx:55]: Not really, added for readability - will remove it.

File: app/actions/definitions/comments.tsx (hunk 6 above)
Comment (hmacr) [reply app/actions/definitions/comments.tsx:59]: Thought of being extra safe and send everythin, but you're right - there could be unnecessary state we may not be interested in that lead to bugs.

File: app/scenes/Document/index.tsx (hunk 5 above)
Comment (tommoor) [reply app/scenes/Document/index.tsx:39]: Feels okay in use... maybe we'll get away with it

**Review by tommoor — APPROVED** [review]

**Review by tommoor — APPROVED** [review]
