### PR TITLE
fix: Code language picker missing

### LINKED ISSUE #10843: Language picker drop-down and copy button are not appearing for code blocks
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This is not related to configuring Outline

- [x] The issue is not related to self-hosting config

### Current Behavior

In Edit Mode, when I click a code block, no coding-language drop-down menu appears.  When not in Edit Mode, when I click a code block, no "Copy" button appears.

### Expected Behavior

The language drop-down menu and "Copy" button should appear when clicking any code block.

### Steps To Reproduce

_No response_

### Environment

```markdown
- Outline: the hosted version
- Browser: Chrome version 143.0.7499.41 (arm64) on macOS
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by tommoor**
closes #10843
regressed in https://github.com/outline/outline/pull/10762

### CODE REVIEW

File: app/editor/components/SelectionToolbar.tsx [hunk 1]
```diff
@@ -254,10 +259,6 @@ export function SelectionToolbar(props: Props) {
     setActiveToolbar(null);
   };
 
-  if (!activeToolbar || !items.length) {
```
Comment (tommoor) [inline app/editor/components/SelectionToolbar.tsx:257]: This also fixes a bug that I think was existing where the first click into a code block would not show the menu due to `menuRef` being undefined

File: app/editor/components/SelectionToolbar.tsx
Comment (apoorv-mishra) [inline app/editor/components/SelectionToolbar.tsx:1]: This seems to have broken the `Cmd-k` shortcut and requires two clicks to open link editor. Plus, if you close the empty link editor, you end up with a `FloatingToolbar` with no items, that looks like a downward arrow in UI.

Comment (tommoor) [reply app/editor/components/SelectionToolbar.tsx:1]: Yea I realized :( 

This stuff is such a mess
