### PR TITLE
fix: Regression with TOC not showing when navigating directly to doc

### LINKED ISSUE #1499: Contents menu empty on reload
The Contents menu open/close state persists across page reloads, but the menu does not regenerate itself on load.

**To Reproduce**
1. Go to a page with a contents menu
2. Click on "Show contents"
3. Reload the page
4. Menu shows: `Headings you add to the document will appear here`

**Expected behavior**
The menu should show the page contents instead of the placeholder text.

**Outline (please complete the following information):**
- Install: self hosted
- Version: `9b5573c5e2`

**Desktop (please complete the following information):**
 - OS: macos
 - Browser chrome, safari
 - Version 84, 13

### PR DESCRIPTION
**Pull request by tommoor**
fixes: Editing document too wide when TOC visible in read only

closes #1499

### CODE REVIEW

File: app/scenes/Document/components/Document.js [hunk 1]
```diff
@@ -412,50 +413,52 @@ class DocumentScene extends React.Component<Props> {
                   )}
                 </Notice>
               )}
-              <Flex auto={!readOnly}>
-                {ui.tocVisible && readOnly && (
-                  <Contents
-                    headings={this.editor ? this.editor.getHeadings() : []}
+              <React.Suspense fallback={<LoadingPlaceholder />}>
```
Comment (tommoor) [inline app/scenes/Document/components/Document.js:416]: Key is to move Suspense boundary outside of TOC
