### PR TITLE
fix: Cleanup user menu

### LINKED ISSUE #4530: Users with long names is outfit dropdown list
Users with long names is outfit dropdown list

**To Reproduce**
1. Go to Settings->Members
2. Try change role user with very long name

**Screenshots**
image

**Outline (please complete the following information):**
- Install:  self hosted
- Version: latest

**Desktop (please complete the following information):**
 - OS: MaxOs
 - Browser Chrome
 - Version 108

I think user name indropdown list is unnecessary

### PR DESCRIPTION
**Pull request by tommoor**
Move confirmation dialogs from window confirmations, last `window.confirm`'s in the codebase.

closes #4530

### CODE REVIEW

File: app/components/Modal.tsx [hunk 1]
```diff
@@ -252,8 +252,9 @@ const Small = styled.div`
   animation: ${fadeAndScaleIn} 250ms ease;
 
   margin: auto auto;
+  width: 30vw;
   min-width: 350px;
-  max-width: 30vw;
```
Comment (tommoor) [inline app/components/Modal.tsx:256]: These were getting a bit wide
