### PR TITLE
fix: Email auth should allow same guest user on multiple subdomains

### LINKED ISSUE #2249: Email auth does not prioritize current subdomain
**To Reproduce**
1. Have multiple accounts with the same email
2. Go to one subdomain
3. Use the email
4. Forwarded to SSO for other subdomain

**Expected behavior**

- Current subdomain should be prioritized

### PR DESCRIPTION
**Pull request by tommoor**
It is possible to invite, say, a contractor `tom@example.com` to two teams – `one.getoutline.com` and `two.getoutline.com`, prior to these changes it was not possible to signin to the second created team via email, even when doing so via the `two.getoutline.com` subdomain.

Now the current domain or subdomain is given precedence.

closes #2249

### CODE REVIEW

File: server/migrations/20170712055148-non-unique-email.js [hunk 1]
```diff
@@ -1,15 +1,7 @@
...
-      type: Sequelize.STRING,
-      unique: false,
-      allowNull: false,
-    });
-    await queryInterface.changeColumn('users', 'username', {
-      type: Sequelize.STRING,
-      unique: false,
-      allowNull: false,
-    });
+    await queryInterface.removeConstraint('users', 'users_email_key', {})
```
Comment (tommoor) [inline server/migrations/20170712055148-non-unique-email.js:3]: Fixes email column indexed as unique in tests.

File: server/test/support.js [hunk 2]
```diff
@@ -3,17 +3,15 @@ import { v4 as uuidv4 } from "uuid";
...
 
-export function flushdb() {
-  const sql = sequelize.getQueryInterface();
-  const tables = Object.keys(sequelize.models).map((model) => {
-    const n = sequelize.models[model].getTableName();
-    return sql.queryGenerator.quoteTable(
-      typeof n === "string" ? n : n.tableName
-    );
-  });
+const sql = sequelize.getQueryInterface();
```
Comment (tommoor) [inline server/test/support.js:6]: Just trying to make tests run slightly faster by not doing these extra steps for every test run. Probably negligible compared to the actual truncation step though.
