### PR TITLE
fix: show all document backlinks for a user

### LINKED ISSUE #7534: Backlinks section should show all documents that the current user has access to
**To Reproduce**
1. Link to a public doc from a private doc
2. Visit the public doc
3. Private doc does not appear in backlinks

**Expected behavior**

The private doc should be listed for the current user.

### PR DESCRIPTION
**Pull request by hmacr**
Closes #7534

### CODE REVIEW

File: server/models/Backlink.ts [hunk 1]
```diff
@@ -37,6 +55,67 @@ class Backlink extends IdModel<
   @ForeignKey(() => Document)
   @Column(DataType.UUID)
   reverseDocumentId: string;
+
+  public static async findSourceDocumentIdsForUser(
```
Comment (tommoor) [inline server/models/Backlink.ts:59]: This works but is quite complicated, I'm worried about bugs – given that `Document.findByPk` already has all the logic to scope to a user in just these lines:

```
https://github.com/outline/outline/blob/7a8d40b9e73454ee70cc5f4320d9e49ba0f48f3c/server/models/Document.ts#L687-L698
```

could we create something similar, perhaps `Document.findByIds` and just pass in the backlink document ID's?

Comment (hmacr) [reply server/models/Backlink.ts:59]: Agreed - We can filter for membership existence for the results from `Document.findByIds` (since the query uses left outer join).

File: server/models/Backlink.ts [hunk 2]
```diff
@@ -37,6 +37,32 @@ class Backlink extends IdModel<
...
+      },
+    });
+
+    const documents = await Document.findByIds(
+      backlinks.map((backlink) => backlink.reverseDocumentId),
+      { userId: user.id }
+    );
+
+    return documents
+      .filter(
```
Comment (tommoor) [inline server/models/Backlink.ts:58]: Did you find this filter was required? I would not expect anything to get filtered here 🤔

File: server/models/Document.ts [hunk 3]
```diff
@@ -733,6 +734,41 @@ class Document extends ArchivableModel<
...
+   * @param options FindOptions
+   * @returns A promise resolving to the list of documents
+   */
+  static async findByIds(
+    ids: string[],
+    options?: Omit<FindOptions<Document>, "where"> &
+      Omit<AdditionalFindOptions, "rejectOnEmpty">
+  ): Promise<Document[]> {
+    const userId = options?.userId;
+    const rest = omit(options, "userId");
```
Comment (tommoor) [inline server/models/Document.ts:751]:
```suggestion
    const { userId, ...rest } = options;
```

preferred? You would have to provide a default value of empty object for `options` is all

File: server/models/Backlink.ts (hunk 1 above)
Comment (tommoor) [reply server/models/Backlink.ts:41]: looking much better

File: server/models/Backlink.ts (hunk 2 above)
Comment (hmacr) [reply server/models/Backlink.ts:58]: I'm afraid, yes. The membership queries use left outer join (`required: false` [here](https://github.com/outline/outline/blob/main/server/models/Document.ts#L192) & [here](https://github.com/outline/outline/blob/main/server/models/Document.ts#L196) ) -  it'd return all the documents requested. We need to get only the source docs that the user has access to.

File: server/models/Document.ts (hunk 3 above)
Comment (hmacr) [reply server/models/Document.ts:751]: `options` is an optional param here. Do we want to make it required?
I was thinking since it's a common `findByIds` method, this could potentially be used as `findByIds(list_of_ids)` in the future.

Comment (tommoor) [reply server/models/Document.ts:751]: `options = {}` solves it

File: server/models/Backlink.ts (hunk 2 above)
Comment (hmacr) [reply server/models/Backlink.ts:58]: An example where the filter is necessary.

UserA: owns DocA and DocS.
UserB: owns DocB and has access to DocS.

Consider DocS has backlinks to DocA & DocB.
For UserA, we should list only DocA (likewise DocB for userB).

Comment (tommoor) [reply server/models/Backlink.ts:58]: Okay, makes sense – but shouldn't we move this filtering into `findByIds` otherwise it would be easy to misuse that method in the future

Comment (hmacr) [reply server/models/Backlink.ts:58]: True - missed it 🤦‍♂️
Filter when "userId" is present.

**Review by tommoor — APPROVED** [review]
