### PR TITLE
fix: Drafts appear in document insert search

### LINKED ISSUE #1147: Drafts should not show when searching to link from a document
- Create a document
- Add some text and hit CMD+K
- In the document search toolbar drafts should not show as results, they currently do.

### PR DESCRIPTION
**Pull request by tommoor**
closes #1147

### CODE REVIEW

File: app/scenes/Search/Search.js [hunk 1]
```diff
@@ -188,6 +188,7 @@ class Search extends React.Component<Props> {
           limit: DEFAULT_PAGINATION_LIMIT,
           dateFilter: this.dateFilter,
           includeArchived: this.includeArchived,
+          includeDrafts: true,
```
Comment (tommoor) [inline app/scenes/Search/Search.js]: Drafts should continue to be returned in the regular search
