### PR TITLE
fix: editing collections should not forward to collection on save

### LINKED ISSUE #3183: Editing collections should not forward to collection on save
Title says it all.

### PR DESCRIPTION
**Pull request by iamsaumya**
closes #3183

### CODE REVIEW

File: app/scenes/CollectionEdit.tsx [hunk 1]
```diff
@@ -40,14 +40,17 @@ const CollectionEdit = ({ collectionId, onSubmit }: Props) => {
...
+        const redirect = location.pathname === collection.url;
         await collection.save({
           name,
           icon,
           color,
           sort,
         });
-        history.push(collection.url);
         onSubmit();
+        if (redirect) {
```
Comment (tommoor) [inline app/scenes/CollectionEdit.tsx:51]: I'm pretty sure this can be entirely removed as there is already a `useEffect` in the CollectionScene to redirect to the canonical url if it changes

File: app/scenes/Collection.tsx [hunk 2]
```diff
@@ -48,14 +48,14 @@ function CollectionScene() {
   const can = usePolicy(collection?.id || "");
 
   React.useEffect(() => {
-    if (collection) {
+    if (collection?.name) {
```
Comment (tommoor) [inline app/scenes/Collection.tsx:51]: Why the change?

Comment (iamsaumya) [reply app/scenes/Collection.tsx:51]: the useEffect wasn't running after the update.

**Review by tommoor — APPROVED** [review]
