### PR TITLE
fix: navigate to all the pages of settings through command bar

### LINKED ISSUE #3053: Navigation to different pages of settings through command bar
We should add actions in the command bar to navigate all the settings pages. All the pages have associated icons, so there is no stopping.

### PR DESCRIPTION
**Pull request by iamsaumya**
closes #3053 

- [x] check if the initial bundle size is increased.

### CODE REVIEW

File: app/actions/definitions/navigation.tsx [hunk 1]
```diff
@@ -57,6 +57,7 @@ export const navigateToRecentSearchQuery = (searchQuery: SearchQuery) =>
     perform: () => history.push(searchPath(searchQuery.query)),
   });
 
+// could be a document action
```
Comment (iamsaumya) [inline app/actions/definitions/navigation.tsx:60]: We need to assign a section to search.

Screenshot 2022-03-11 at 2 07 23 AM

**Comment by iamsaumya** [comment]
RelativeCI doesn't reflect any major increase. good to go

File: app/hooks/useSettingsAction.tsx [hunk 2]
```diff
@@ -0,0 +1,23 @@
+import React from "react";
```
Comment (tommoor) [inline app/hooks/useSettingsAction.tsx:1]:
```suggestion
import * as React from "react";
```

Prefer for consistency

File: app/hooks/useSettingsAction.tsx [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+import { createAction } from "~/actions";
+import history from "~/utils/history";
+import useAuthorizedSettingsConfig from "./useAuthorizedSettingsConfig";
+
+const useSettingsActions = () => {
+  const config = useAuthorizedSettingsConfig();
+  const actions = React.useMemo(() => {
+    return config.map((item) => {
+      const Icon = item.icon;
+      return createAction({
```
Comment (tommoor) [inline app/hooks/useSettingsAction.tsx:11]: I'd say we want these to be children of the "Settings" action, because it's a bit confusing in your screenshot. With the parent it would read "Settings -> Features" for example, and child actions are still searchable

File: app/routes/settings.tsx [hunk 4]
```diff
@@ -1,42 +1,25 @@
...
-import Zapier from "~/scenes/Settings/Zapier";
 import Route from "~/components/ProfiledRoute";
-import env from "~/env";
-
-const isHosted = env.DEPLOYMENT === "hosted";
+import useAuthorizedSettingsConfig from "~/hooks/useAuthorizedSettingsConfig";
 
 export default function SettingsRoutes() {
+  const configs = useAuthorizedSettingsConfig();
+  const Routes = React.useMemo(
```
Comment (tommoor) [inline app/routes/settings.tsx:8]: No need for the memo here, just inline the map

File: app/hooks/useAuthorizedSettingsConfig.ts [hunk 5]
```diff
@@ -0,0 +1,196 @@
...
+  | "Shares"
+  | "Import"
+  | "Export"
+  | "Slack"
+  | "Zapier";
+
+export type ConfigItem = {
+  name: string;
+  path: string;
+  icon: typeof NewDocumentIcon;
```
Comment (tommoor) [inline app/hooks/useAuthorizedSettingsConfig.ts:54]:
```suggestion
  icon: typeof NewDocumentIcon;
```

This type seems funky

**Review by tommoor — COMMENTED** [review]
_almost_ – thank you

File: app/hooks/useSettingsAction.tsx (hunk 3 above)
Comment (iamsaumya) [reply app/hooks/useSettingsAction.tsx:11]: What would be the group of the parent "Settings" action?

Comment (tommoor) [reply app/hooks/useSettingsAction.tsx:11]: I think "Navigation" would be fine

**Review by tommoor — APPROVED** [review]
Noice 👏
