### PR TITLE
fix: Sidebar jumps when publish or unpublish document

### LINKED ISSUE #4702: Publishing or unpublishing a doc is janky in sidebar
When a document is published or unpublished the sidebar shows a flash where the document has disappeared, this makes the whole experience feel a lot less "solid" – we should find a way around this.

### PR DESCRIPTION
**Pull request by tommoor**
Updated the API to return the collection that's already in memory so that everything can be updated at once.

closes #4702

### CODE REVIEW

File: app/components/Sidebar/components/SidebarLink.tsx [hunk 1]
```diff
@@ -194,8 +196,17 @@ const Link = styled(NavLink)<{
   ${(props) =>
     props.$isDraft &&
     css`
-      padding: 4px 14px;
```
Comment (tommoor) [inline app/components/Sidebar/components/SidebarLink.tsx:197]: Now that the update is seamless it made it obvious that drafts are slightly differently sized on desktop

File: app/stores/DocumentsStore.ts [hunk 2]
```diff
@@ -763,16 +772,16 @@ export default class DocumentsStore extends BaseStore<Document> {
...
       invariant(res?.data, "Data should be available");
-      document.updateFromJson(res.data);
+      document.updateFromJson(res.data.document);
+      const collection = this.getCollectionForDocument(document);
+      collection?.updateFromJson(res.data.collection);
       this.addPolicies(res.policies);
     });
-    const collection = this.getCollectionForDocument(document);
-    if (collection) {
-      collection.refresh();
```
Comment (tommoor) [inline app/stores/DocumentsStore.ts:774]: Avoids an extra API request here, so that's nice.
