### PR TITLE
fix: Nested document menu item appears where it shouldn't

### LINKED ISSUE #1191: "New nested document" appears as option on drafts
However it's not possible to create a nested document of a draft currently – it errors. So we should disable the item in this scenario until such functionality exists.

Reported via support.

### PR DESCRIPTION
**Pull request by tommoor**
fix: "Publish" item is disabled when it shouldn't be

closes #1191

### CODE REVIEW

File: app/menus/DocumentMenu.js [hunk 1]
```diff
@@ -185,7 +185,7 @@ class DocumentMenu extends React.Component<Props> {
             </DropdownMenuItem>
           </React.Fragment>
         )}
-        {can.update && (
+        {can.createChildDocument && (
```
Comment (tommoor) [inline app/menus/DocumentMenu.js]: Introduced a new policy for this 👍

File: app/scenes/Document/components/Document.js [hunk 2]
```diff
@@ -80,6 +80,10 @@ class DocumentScene extends React.Component<Props> {
     this.loadEditor();
   }
 
+  componentDidMount() {
+    this.updateIsDirty();
```
Comment (tommoor) [inline app/scenes/Document/components/Document.js]: Should check policy on mount
