### PR TITLE
Map keyboard shortcuts on windows

### LINKED ISSUE #525: (Some) Shortcuts not working for Windows
The shortcuts that use the command (Mac) key does not seem to have an alternate in Windows. I tried using Ctrl, Win, Alt and Shift key as a replacement for ⌘, but didn't work. Eg: ⌘+b for bold, ⌘+/ for shortcuts guide.
As an alternative, I suggest the use of the Ctrl key for Windows. Ctrl is used for all formatting shortcuts in Windows.

My setup: Windows 10 (64 bit), Chrome v63.

### PR DESCRIPTION
**Pull request by jorilallo**
`event.metaKey` maps to Windows key and not the Ctrl so keyboard shortcuts weren't working on Windows.

Fixes #525

### CODE REVIEW

**Comment by jorilallo** [comment]
Looks like this is not the only place, refactoring so no need to review yet

File: app/scenes/KeyboardShortcuts/KeyboardShortcuts.js [hunk 1]
```diff
@@ -38,7 +38,7 @@ function KeyboardShortcuts() {
         <Label>Jump to dashboard</Label>
 
         <Keys>
-          <Key>⌘</Key> + <Key>/</Key>
+          <Key>?</Key>
```
Comment (tommoor) [inline app/scenes/KeyboardShortcuts/KeyboardShortcuts.js]: 💯
