### PR TITLE
fix: Improve handling of suspended users signing in with email

### LINKED ISSUE #1740: Attempting to sign-in via email to a suspended account is not well handled
Sentry Issue: [OUTLINE-CLOUD-M0](https://sentry.io/organizations/outline-jl/issues/1926632887/?referrer=github_integration)

```
ForbiddenError: Your access has been suspended by the team admin
  File "/app/build/server/errors.js", line 43, in new UserSuspendedError
    return (0, _httpErrors.default)(403, "Your access has been suspended by the team admin", {
  File "/app/build/server/middlewares/authentication.js", line 97, in authMiddleware
    throw new _errors.UserSuspendedError({
  ?, in runMicrotasks
```

### PR DESCRIPTION
**Pull request by tommoor**
refactor: Separate `signIn` method from `auth` middleware
fix: Email signin token parsed by JWT middleware
fix: User marked as "active" when logging in as suspended with email
fix: Suspended email signin correctly redirected to login screen

closes #1740

### CODE REVIEW

File: server/auth/providers/email.js [hunk 1]
```diff
@@ -84,25 +84,26 @@ router.post("email", async (ctx) => {
...
   try {
     const user = await getUserForEmailSigninToken(token);
-
-    const team = await Team.findByPk(user.teamId);
-    if (!team.guestSignin) {
-      throw new AuthorizationError();
+    if (!user.team.guestSignin) {
+      return ctx.redirect("/?notice=auth-error");
+    }
+    if (user.isSuspended) {
```
Comment (tommoor) [inline server/auth/providers/email.js:97]: We need to check and redirect _before_ marking the user as active, previously this was done inside of `signIn`

File: server/auth/providers/email.js [hunk 2]
```diff
@@ -84,25 +84,26 @@ router.post("email", async (ctx) => {
...
 
   ctx.assertPresent(token, "token is required");
 
   try {
     const user = await getUserForEmailSigninToken(token);
-
-    const team = await Team.findByPk(user.teamId);
-    if (!team.guestSignin) {
-      throw new AuthorizationError();
+    if (!user.team.guestSignin) {
```
Comment (tommoor) [inline server/auth/providers/email.js:94]: No point re-querying team, we now always load it with `user`.

File: server/middlewares/authentication.js [hunk 3]
```diff
@@ -94,78 +91,6 @@ export default function auth(options?: { required?: boolean } = {}) {
       ctx.state.user = user;
     }
 
-    ctx.signIn = (user: User, team: Team, service, isFirstSignin = false) => {
```
Comment (tommoor) [inline server/middlewares/authentication.js:97]: Moved to `util` method rather than bundling with authentication middleware, as this meant to get the `signIn` method you also had to have token parsing in the stack.
